// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ivhpgazgw15hPKwKsPQEWr
// Component: H5-tROgca9
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_game_schedule.module.css"; // plasmic-import: ivhpgazgw15hPKwKsPQEWr/projectcss
import sty from "./PlasmicLoginPage.module.css"; // plasmic-import: H5-tROgca9/css
import Ellipse17Icon from "./icons/PlasmicIcon__Ellipse17"; // plasmic-import: YC0SEe5Fs/icon
import Ellipse18Icon from "./icons/PlasmicIcon__Ellipse18"; // plasmic-import: 5sKiHVAP5w/icon
import Vector1StrokeIcon from "./icons/PlasmicIcon__Vector1Stroke"; // plasmic-import: dd_eaW0X0s/icon
import SocialIcon from "./icons/PlasmicIcon__Social"; // plasmic-import: 30NfKzi4H_/icon
import Vector1Stroke4Icon from "./icons/PlasmicIcon__Vector1Stroke4"; // plasmic-import: DzqyvHh9hmS/icon
import Vector1Stroke3Icon from "./icons/PlasmicIcon__Vector1Stroke3"; // plasmic-import: -xDb8fKqBYH/icon

export const PlasmicLoginPage__VariantProps = new Array();

export const PlasmicLoginPage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicLoginPage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"loginPage"}
            data-plasmic-override={overrides.loginPage}
            className={classNames(projectcss.all, sty.loginPage)}
          >
            <div
              data-plasmic-name={"hero"}
              data-plasmic-override={overrides.hero}
              className={classNames(projectcss.all, sty.hero)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__pbzyW)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__u9HKj
                  )}
                >
                  {"Sign In"}
                </div>
                {false ? (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___67NgV
                    )}
                  >
                    {"Launching Soon"}
                  </div>
                ) : null}
              </div>
              {false ? (
                <div
                  data-plasmic-name={"graphic"}
                  data-plasmic-override={overrides.graphic}
                  className={classNames(projectcss.all, sty.graphic)}
                >
                  <Ellipse17Icon
                    className={classNames(projectcss.all, sty.svg__o62LV)}
                    role={"img"}
                  />

                  <Ellipse18Icon
                    className={classNames(projectcss.all, sty.svg__bgk7N)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={
                      "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
                    }
                    data-plasmic-override={
                      overrides.design82A0Ada5644E4B87Ae4188Faf9684Ea311
                    }
                    className={classNames(
                      projectcss.all,
                      sty.design82A0Ada5644E4B87Ae4188Faf9684Ea311
                    )}
                  />
                </div>
              ) : null}
            </div>
            <div
              data-plasmic-name={"form"}
              data-plasmic-override={overrides.form}
              className={classNames(projectcss.all, sty.form)}
            >
              <div
                data-plasmic-name={"sectionForgot"}
                data-plasmic-override={overrides.sectionForgot}
                className={classNames(projectcss.all, sty.sectionForgot)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lcSpo
                  )}
                >
                  {"Forgot password?"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jOg8
                  )}
                >
                  {"Remember me"}
                </div>
                <div
                  data-plasmic-name={"rectangle1"}
                  data-plasmic-override={overrides.rectangle1}
                  className={classNames(projectcss.all, sty.rectangle1)}
                />
              </div>
              <div
                data-plasmic-name={"loginBtn"}
                data-plasmic-override={overrides.loginBtn}
                className={classNames(projectcss.all, sty.loginBtn)}
              >
                <a
                  data-plasmic-name={"rectangle"}
                  data-plasmic-override={overrides.rectangle}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.rectangle
                  )}
                  href={`/new-page-4`}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ayBUe
                  )}
                >
                  {"login"}
                </div>
              </div>
              <div
                data-plasmic-name={"password"}
                data-plasmic-override={overrides.password}
                className={classNames(projectcss.all, sty.password)}
              >
                <div
                  data-plasmic-name={"rectangle2"}
                  data-plasmic-override={overrides.rectangle2}
                  className={classNames(projectcss.all, sty.rectangle2)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uuEp
                  )}
                >
                  {"Password"}
                </div>
              </div>
              <div
                data-plasmic-name={"username"}
                data-plasmic-override={overrides.username}
                className={classNames(projectcss.all, sty.username)}
              >
                <div
                  data-plasmic-name={"rectangle3"}
                  data-plasmic-override={overrides.rectangle3}
                  className={classNames(projectcss.all, sty.rectangle3)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__j9RSn
                  )}
                >
                  {"Login"}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <div
                data-plasmic-name={"bottom"}
                data-plasmic-override={overrides.bottom}
                className={classNames(projectcss.all, sty.bottom)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__z9FPd
                  )}
                >
                  {"© Copyright 2022 GameSchedule"}
                </div>
              </div>
              <div
                data-plasmic-name={"right"}
                data-plasmic-override={overrides.right}
                className={classNames(projectcss.all, sty.right)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sDqSx
                  )}
                >
                  {"About\nTerms\nLegal"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4Dw4S
                  )}
                >
                  {"Press\nSupport"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__neY2Y
                  )}
                >
                  {"Twitter\nInstagram"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vwVtf
                  )}
                >
                  {"About"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wliKs
                  )}
                >
                  {"Contact"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d83L
                  )}
                >
                  {"Social"}
                </div>
              </div>
              <div
                data-plasmic-name={"left"}
                data-plasmic-override={overrides.left}
                className={classNames(projectcss.all, sty.left)}
              >
                <div
                  data-plasmic-name={"logo"}
                  data-plasmic-override={overrides.logo}
                  className={classNames(projectcss.all, sty.logo)}
                >
                  <Vector1StrokeIcon
                    className={classNames(projectcss.all, sty.svg__pYjy)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"nftlanding"}
                    data-plasmic-override={overrides.nftlanding}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.nftlanding
                    )}
                  >
                    {"gameschedule"}
                  </div>
                </div>
                <SocialIcon
                  className={classNames(projectcss.all, sty.svg___2R2Dt)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"divider"}
                data-plasmic-override={overrides.divider}
                className={classNames(projectcss.all, sty.divider)}
              >
                <div
                  data-plasmic-name={"rectangle9"}
                  data-plasmic-override={overrides.rectangle9}
                  className={classNames(projectcss.all, sty.rectangle9)}
                />
              </div>
            </div>
            <div
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(projectcss.all, sty.header)}
            >
              <div
                data-plasmic-name={"logo2"}
                data-plasmic-override={overrides.logo2}
                className={classNames(projectcss.all, sty.logo2)}
              >
                <Vector1Stroke4Icon
                  className={classNames(projectcss.all, sty.svg__kJrjt)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"nftlanding2"}
                  data-plasmic-override={overrides.nftlanding2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.nftlanding2
                  )}
                >
                  {"gameschedule"}
                </div>
              </div>
              <p.Stack
                as={"div"}
                data-plasmic-name={"navigation"}
                data-plasmic-override={overrides.navigation}
                hasGap={true}
                className={classNames(projectcss.all, sty.navigation)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__piC8
                  )}
                >
                  {"Features"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__u0Mus
                  )}
                >
                  {"About"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yorhj
                  )}
                >
                  {"Launch"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fz46Q
                  )}
                >
                  {"Sign Up"}
                </div>
              </p.Stack>
            </div>
            <Vector1Stroke3Icon
              className={classNames(projectcss.all, sty.svg__duhwO)}
              role={"img"}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "loginPage",
    "hero",
    "graphic",
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311",
    "form",
    "sectionForgot",
    "rectangle1",
    "loginBtn",
    "rectangle",
    "password",
    "rectangle2",
    "username",
    "rectangle3",
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9",
    "header",
    "logo2",
    "nftlanding2",
    "navigation"
  ],

  loginPage: [
    "loginPage",
    "hero",
    "graphic",
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311",
    "form",
    "sectionForgot",
    "rectangle1",
    "loginBtn",
    "rectangle",
    "password",
    "rectangle2",
    "username",
    "rectangle3",
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9",
    "header",
    "logo2",
    "nftlanding2",
    "navigation"
  ],

  hero: ["hero", "graphic", "design82A0Ada5644E4B87Ae4188Faf9684Ea311"],
  graphic: ["graphic", "design82A0Ada5644E4B87Ae4188Faf9684Ea311"],
  design82A0Ada5644E4B87Ae4188Faf9684Ea311: [
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
  ],

  form: [
    "form",
    "sectionForgot",
    "rectangle1",
    "loginBtn",
    "rectangle",
    "password",
    "rectangle2",
    "username",
    "rectangle3"
  ],

  sectionForgot: ["sectionForgot", "rectangle1"],
  rectangle1: ["rectangle1"],
  loginBtn: ["loginBtn", "rectangle"],
  rectangle: ["rectangle"],
  password: ["password", "rectangle2"],
  rectangle2: ["rectangle2"],
  username: ["username", "rectangle3"],
  rectangle3: ["rectangle3"],
  footer: [
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9"
  ],

  bottom: ["bottom"],
  right: ["right"],
  left: ["left", "logo", "nftlanding"],
  logo: ["logo", "nftlanding"],
  nftlanding: ["nftlanding"],
  divider: ["divider", "rectangle9"],
  rectangle9: ["rectangle9"],
  header: ["header", "logo2", "nftlanding2", "navigation"],
  logo2: ["logo2", "nftlanding2"],
  nftlanding2: ["nftlanding2"],
  navigation: ["navigation"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLoginPage__ArgProps,
          internalVariantPropNames: PlasmicLoginPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLoginPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLoginPage";
  } else {
    func.displayName = `PlasmicLoginPage.${nodeName}`;
  }
  return func;
}

export const PlasmicLoginPage = Object.assign(
  // Top-level PlasmicLoginPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    loginPage: makeNodeComponent("loginPage"),
    hero: makeNodeComponent("hero"),
    graphic: makeNodeComponent("graphic"),
    design82A0Ada5644E4B87Ae4188Faf9684Ea311: makeNodeComponent(
      "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
    ),
    form: makeNodeComponent("form"),
    sectionForgot: makeNodeComponent("sectionForgot"),
    rectangle1: makeNodeComponent("rectangle1"),
    loginBtn: makeNodeComponent("loginBtn"),
    rectangle: makeNodeComponent("rectangle"),
    password: makeNodeComponent("password"),
    rectangle2: makeNodeComponent("rectangle2"),
    username: makeNodeComponent("username"),
    rectangle3: makeNodeComponent("rectangle3"),
    footer: makeNodeComponent("footer"),
    bottom: makeNodeComponent("bottom"),
    right: makeNodeComponent("right"),
    left: makeNodeComponent("left"),
    logo: makeNodeComponent("logo"),
    nftlanding: makeNodeComponent("nftlanding"),
    divider: makeNodeComponent("divider"),
    rectangle9: makeNodeComponent("rectangle9"),
    header: makeNodeComponent("header"),
    logo2: makeNodeComponent("logo2"),
    nftlanding2: makeNodeComponent("nftlanding2"),
    navigation: makeNodeComponent("navigation"),
    // Metadata about props expected for PlasmicLoginPage
    internalVariantProps: PlasmicLoginPage__VariantProps,
    internalArgProps: PlasmicLoginPage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicLoginPage;
/* prettier-ignore-end */
