// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ivhpgazgw15hPKwKsPQEWr
// Component: U76_uR0os0
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_game_schedule.module.css"; // plasmic-import: ivhpgazgw15hPKwKsPQEWr/projectcss
import sty from "./PlasmicCalendarPage4.module.css"; // plasmic-import: U76_uR0os0/css
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: wqQxD5TEKa/icon
import ArrowLeftIcon from "./icons/PlasmicIcon__ArrowLeft"; // plasmic-import: LWD6uGxiaP/icon
import ChevronLeftIcon from "./icons/PlasmicIcon__ChevronLeft"; // plasmic-import: oaINC_mE27/icon
import ArrowRight2Icon from "./icons/PlasmicIcon__ArrowRight2"; // plasmic-import: J51gYEzBJp/icon
import ChevronRightIcon from "./icons/PlasmicIcon__ChevronRight"; // plasmic-import: qRioISSCsU/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: z1kTwBx_qd/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: F4m3gz-3un/icon

export const PlasmicCalendarPage4__VariantProps = new Array();

export const PlasmicCalendarPage4__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicCalendarPage4__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"calendarPage4"}
            data-plasmic-override={overrides.calendarPage4}
            className={classNames(projectcss.all, sty.calendarPage4)}
          >
            <div
              data-plasmic-name={"cardBg"}
              data-plasmic-override={overrides.cardBg}
              className={classNames(projectcss.all, sty.cardBg)}
            />

            <div
              data-plasmic-name={"selectorTable"}
              data-plasmic-override={overrides.selectorTable}
              className={classNames(projectcss.all, sty.selectorTable)}
            >
              <div
                data-plasmic-name={"column4"}
                data-plasmic-override={overrides.column4}
                className={classNames(projectcss.all, sty.column4)}
              >
                <div
                  data-plasmic-name={"timeSelector"}
                  data-plasmic-override={overrides.timeSelector}
                  className={classNames(projectcss.all, sty.timeSelector)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg"}
                      data-plasmic-override={overrides.disabledBg}
                      className={classNames(projectcss.all, sty.disabledBg)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg"}
                      data-plasmic-override={overrides.enabledBg}
                      className={classNames(projectcss.all, sty.enabledBg)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg"}
                    data-plasmic-override={overrides.outlineBg}
                    className={classNames(projectcss.all, sty.outlineBg)}
                  />

                  <div
                    data-plasmic-name={"placeholder"}
                    data-plasmic-override={overrides.placeholder}
                    className={classNames(projectcss.all, sty.placeholder)}
                  >
                    <div
                      data-plasmic-name={"placeholder2"}
                      data-plasmic-override={overrides.placeholder2}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder2
                      )}
                    >
                      {"12:00 AM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector2"}
                  data-plasmic-override={overrides.timeSelector2}
                  className={classNames(projectcss.all, sty.timeSelector2)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg2"}
                      data-plasmic-override={overrides.disabledBg2}
                      className={classNames(projectcss.all, sty.disabledBg2)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg2"}
                      data-plasmic-override={overrides.enabledBg2}
                      className={classNames(projectcss.all, sty.enabledBg2)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg2"}
                    data-plasmic-override={overrides.outlineBg2}
                    className={classNames(projectcss.all, sty.outlineBg2)}
                  />

                  <div
                    data-plasmic-name={"placeholder3"}
                    data-plasmic-override={overrides.placeholder3}
                    className={classNames(projectcss.all, sty.placeholder3)}
                  >
                    <div
                      data-plasmic-name={"placeholder4"}
                      data-plasmic-override={overrides.placeholder4}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder4
                      )}
                    >
                      {"11:30 PM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector3"}
                  data-plasmic-override={overrides.timeSelector3}
                  className={classNames(projectcss.all, sty.timeSelector3)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg3"}
                      data-plasmic-override={overrides.disabledBg3}
                      className={classNames(projectcss.all, sty.disabledBg3)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg3"}
                      data-plasmic-override={overrides.enabledBg3}
                      className={classNames(projectcss.all, sty.enabledBg3)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg3"}
                    data-plasmic-override={overrides.outlineBg3}
                    className={classNames(projectcss.all, sty.outlineBg3)}
                  />

                  <div
                    data-plasmic-name={"placeholder5"}
                    data-plasmic-override={overrides.placeholder5}
                    className={classNames(projectcss.all, sty.placeholder5)}
                  >
                    <div
                      data-plasmic-name={"placeholder6"}
                      data-plasmic-override={overrides.placeholder6}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder6
                      )}
                    >
                      {"11:00 PM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector4"}
                  data-plasmic-override={overrides.timeSelector4}
                  className={classNames(projectcss.all, sty.timeSelector4)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg4"}
                      data-plasmic-override={overrides.disabledBg4}
                      className={classNames(projectcss.all, sty.disabledBg4)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg4"}
                      data-plasmic-override={overrides.enabledBg4}
                      className={classNames(projectcss.all, sty.enabledBg4)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg4"}
                    data-plasmic-override={overrides.outlineBg4}
                    className={classNames(projectcss.all, sty.outlineBg4)}
                  />

                  <div
                    data-plasmic-name={"placeholder7"}
                    data-plasmic-override={overrides.placeholder7}
                    className={classNames(projectcss.all, sty.placeholder7)}
                  >
                    <div
                      data-plasmic-name={"placeholder8"}
                      data-plasmic-override={overrides.placeholder8}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder8
                      )}
                    >
                      {"10:30 PM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector5"}
                  data-plasmic-override={overrides.timeSelector5}
                  className={classNames(projectcss.all, sty.timeSelector5)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg5"}
                      data-plasmic-override={overrides.disabledBg5}
                      className={classNames(projectcss.all, sty.disabledBg5)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg5"}
                      data-plasmic-override={overrides.enabledBg5}
                      className={classNames(projectcss.all, sty.enabledBg5)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg5"}
                    data-plasmic-override={overrides.outlineBg5}
                    className={classNames(projectcss.all, sty.outlineBg5)}
                  />

                  <div
                    data-plasmic-name={"placeholder9"}
                    data-plasmic-override={overrides.placeholder9}
                    className={classNames(projectcss.all, sty.placeholder9)}
                  >
                    <div
                      data-plasmic-name={"placeholder10"}
                      data-plasmic-override={overrides.placeholder10}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder10
                      )}
                    >
                      {"10:00 PM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"overline"}
                  data-plasmic-override={overrides.overline}
                  className={classNames(projectcss.all, sty.overline)}
                >
                  <div
                    data-plasmic-name={"overline2"}
                    data-plasmic-override={overrides.overline2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.overline2
                    )}
                  >
                    {"NIGHT"}
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"column3"}
                data-plasmic-override={overrides.column3}
                className={classNames(projectcss.all, sty.column3)}
              >
                <div
                  data-plasmic-name={"timeSelector6"}
                  data-plasmic-override={overrides.timeSelector6}
                  className={classNames(projectcss.all, sty.timeSelector6)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg6"}
                      data-plasmic-override={overrides.disabledBg6}
                      className={classNames(projectcss.all, sty.disabledBg6)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg6"}
                      data-plasmic-override={overrides.enabledBg6}
                      className={classNames(projectcss.all, sty.enabledBg6)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg6"}
                    data-plasmic-override={overrides.outlineBg6}
                    className={classNames(projectcss.all, sty.outlineBg6)}
                  />

                  <div
                    data-plasmic-name={"placeholder11"}
                    data-plasmic-override={overrides.placeholder11}
                    className={classNames(projectcss.all, sty.placeholder11)}
                  >
                    <div
                      data-plasmic-name={"placeholder12"}
                      data-plasmic-override={overrides.placeholder12}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder12
                      )}
                    >
                      {"9:00 PM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector7"}
                  data-plasmic-override={overrides.timeSelector7}
                  className={classNames(projectcss.all, sty.timeSelector7)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg7"}
                      data-plasmic-override={overrides.disabledBg7}
                      className={classNames(projectcss.all, sty.disabledBg7)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg7"}
                      data-plasmic-override={overrides.enabledBg7}
                      className={classNames(projectcss.all, sty.enabledBg7)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg7"}
                    data-plasmic-override={overrides.outlineBg7}
                    className={classNames(projectcss.all, sty.outlineBg7)}
                  />

                  <div
                    data-plasmic-name={"placeholder13"}
                    data-plasmic-override={overrides.placeholder13}
                    className={classNames(projectcss.all, sty.placeholder13)}
                  >
                    <div
                      data-plasmic-name={"placeholder14"}
                      data-plasmic-override={overrides.placeholder14}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder14
                      )}
                    >
                      {"8:00 PM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector8"}
                  data-plasmic-override={overrides.timeSelector8}
                  className={classNames(projectcss.all, sty.timeSelector8)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg8"}
                      data-plasmic-override={overrides.disabledBg8}
                      className={classNames(projectcss.all, sty.disabledBg8)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg8"}
                      data-plasmic-override={overrides.enabledBg8}
                      className={classNames(projectcss.all, sty.enabledBg8)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg8"}
                    data-plasmic-override={overrides.outlineBg8}
                    className={classNames(projectcss.all, sty.outlineBg8)}
                  />

                  <div
                    data-plasmic-name={"placeholder15"}
                    data-plasmic-override={overrides.placeholder15}
                    className={classNames(projectcss.all, sty.placeholder15)}
                  >
                    <div
                      data-plasmic-name={"placeholder16"}
                      data-plasmic-override={overrides.placeholder16}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder16
                      )}
                    >
                      {"7:00 PM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector9"}
                  data-plasmic-override={overrides.timeSelector9}
                  className={classNames(projectcss.all, sty.timeSelector9)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg9"}
                      data-plasmic-override={overrides.disabledBg9}
                      className={classNames(projectcss.all, sty.disabledBg9)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg9"}
                      data-plasmic-override={overrides.enabledBg9}
                      className={classNames(projectcss.all, sty.enabledBg9)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg9"}
                    data-plasmic-override={overrides.outlineBg9}
                    className={classNames(projectcss.all, sty.outlineBg9)}
                  />

                  <div
                    data-plasmic-name={"placeholder17"}
                    data-plasmic-override={overrides.placeholder17}
                    className={classNames(projectcss.all, sty.placeholder17)}
                  >
                    <div
                      data-plasmic-name={"placeholder18"}
                      data-plasmic-override={overrides.placeholder18}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder18
                      )}
                    >
                      {"6:00 PM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector10"}
                  data-plasmic-override={overrides.timeSelector10}
                  className={classNames(projectcss.all, sty.timeSelector10)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg10"}
                      data-plasmic-override={overrides.disabledBg10}
                      className={classNames(projectcss.all, sty.disabledBg10)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg10"}
                      data-plasmic-override={overrides.enabledBg10}
                      className={classNames(projectcss.all, sty.enabledBg10)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg10"}
                    data-plasmic-override={overrides.outlineBg10}
                    className={classNames(projectcss.all, sty.outlineBg10)}
                  />

                  <div
                    data-plasmic-name={"placeholder19"}
                    data-plasmic-override={overrides.placeholder19}
                    className={classNames(projectcss.all, sty.placeholder19)}
                  >
                    <div
                      data-plasmic-name={"placeholder20"}
                      data-plasmic-override={overrides.placeholder20}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder20
                      )}
                    >
                      {"5:00 PM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"overline3"}
                  data-plasmic-override={overrides.overline3}
                  className={classNames(projectcss.all, sty.overline3)}
                >
                  <div
                    data-plasmic-name={"overline4"}
                    data-plasmic-override={overrides.overline4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.overline4
                    )}
                  >
                    {"Evening"}
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"column2"}
                data-plasmic-override={overrides.column2}
                className={classNames(projectcss.all, sty.column2)}
              >
                <div
                  data-plasmic-name={"timeSelector11"}
                  data-plasmic-override={overrides.timeSelector11}
                  className={classNames(projectcss.all, sty.timeSelector11)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg11"}
                      data-plasmic-override={overrides.disabledBg11}
                      className={classNames(projectcss.all, sty.disabledBg11)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg11"}
                      data-plasmic-override={overrides.enabledBg11}
                      className={classNames(projectcss.all, sty.enabledBg11)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg11"}
                    data-plasmic-override={overrides.outlineBg11}
                    className={classNames(projectcss.all, sty.outlineBg11)}
                  />

                  <div
                    data-plasmic-name={"placeholder21"}
                    data-plasmic-override={overrides.placeholder21}
                    className={classNames(projectcss.all, sty.placeholder21)}
                  >
                    <div
                      data-plasmic-name={"placeholder22"}
                      data-plasmic-override={overrides.placeholder22}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder22
                      )}
                    >
                      {"4:00 PM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector12"}
                  data-plasmic-override={overrides.timeSelector12}
                  className={classNames(projectcss.all, sty.timeSelector12)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg12"}
                      data-plasmic-override={overrides.disabledBg12}
                      className={classNames(projectcss.all, sty.disabledBg12)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg12"}
                      data-plasmic-override={overrides.enabledBg12}
                      className={classNames(projectcss.all, sty.enabledBg12)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg12"}
                    data-plasmic-override={overrides.outlineBg12}
                    className={classNames(projectcss.all, sty.outlineBg12)}
                  />

                  <div
                    data-plasmic-name={"placeholder23"}
                    data-plasmic-override={overrides.placeholder23}
                    className={classNames(projectcss.all, sty.placeholder23)}
                  >
                    <div
                      data-plasmic-name={"placeholder24"}
                      data-plasmic-override={overrides.placeholder24}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder24
                      )}
                    >
                      {"3:00 PM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector13"}
                  data-plasmic-override={overrides.timeSelector13}
                  className={classNames(projectcss.all, sty.timeSelector13)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg13"}
                      data-plasmic-override={overrides.disabledBg13}
                      className={classNames(projectcss.all, sty.disabledBg13)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg13"}
                      data-plasmic-override={overrides.enabledBg13}
                      className={classNames(projectcss.all, sty.enabledBg13)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg13"}
                    data-plasmic-override={overrides.outlineBg13}
                    className={classNames(projectcss.all, sty.outlineBg13)}
                  />

                  <div
                    data-plasmic-name={"placeholder25"}
                    data-plasmic-override={overrides.placeholder25}
                    className={classNames(projectcss.all, sty.placeholder25)}
                  >
                    <div
                      data-plasmic-name={"placeholder26"}
                      data-plasmic-override={overrides.placeholder26}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder26
                      )}
                    >
                      {"2:00 PM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector14"}
                  data-plasmic-override={overrides.timeSelector14}
                  className={classNames(projectcss.all, sty.timeSelector14)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg14"}
                      data-plasmic-override={overrides.disabledBg14}
                      className={classNames(projectcss.all, sty.disabledBg14)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"enabledBg14"}
                    data-plasmic-override={overrides.enabledBg14}
                    className={classNames(projectcss.all, sty.enabledBg14)}
                  />

                  <div
                    data-plasmic-name={"outlineBg14"}
                    data-plasmic-override={overrides.outlineBg14}
                    className={classNames(projectcss.all, sty.outlineBg14)}
                  />

                  <div
                    data-plasmic-name={"placeholder27"}
                    data-plasmic-override={overrides.placeholder27}
                    className={classNames(projectcss.all, sty.placeholder27)}
                  >
                    <div
                      data-plasmic-name={"placeholder28"}
                      data-plasmic-override={overrides.placeholder28}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder28
                      )}
                    >
                      {"1:00 PM"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"h3"}
                    data-plasmic-override={overrides.h3}
                    className={classNames(projectcss.all, sty.h3)}
                  >
                    <div
                      data-plasmic-name={"h32"}
                      data-plasmic-override={overrides.h32}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.h32
                      )}
                    >
                      {"Apex Legends"}
                    </div>
                  </div>
                  <ChevronDownIcon
                    className={classNames(projectcss.all, sty.svg___73Y5E)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"rectangle40"}
                    data-plasmic-override={overrides.rectangle40}
                    className={classNames(projectcss.all, sty.rectangle40)}
                  />

                  <div
                    data-plasmic-name={
                      "avatarhumanmanprofileicon13200858767166282345"
                    }
                    data-plasmic-override={
                      overrides.avatarhumanmanprofileicon13200858767166282345
                    }
                    className={classNames(
                      projectcss.all,
                      sty.avatarhumanmanprofileicon13200858767166282345
                    )}
                  />
                </div>
                <div
                  data-plasmic-name={"timeSelector15"}
                  data-plasmic-override={overrides.timeSelector15}
                  className={classNames(projectcss.all, sty.timeSelector15)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg15"}
                      data-plasmic-override={overrides.disabledBg15}
                      className={classNames(projectcss.all, sty.disabledBg15)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg15"}
                      data-plasmic-override={overrides.enabledBg15}
                      className={classNames(projectcss.all, sty.enabledBg15)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg15"}
                    data-plasmic-override={overrides.outlineBg15}
                    className={classNames(projectcss.all, sty.outlineBg15)}
                  />

                  <div
                    data-plasmic-name={"placeholder29"}
                    data-plasmic-override={overrides.placeholder29}
                    className={classNames(projectcss.all, sty.placeholder29)}
                  >
                    <div
                      data-plasmic-name={"placeholder30"}
                      data-plasmic-override={overrides.placeholder30}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder30
                      )}
                    >
                      {"12:00 PM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"overline5"}
                  data-plasmic-override={overrides.overline5}
                  className={classNames(projectcss.all, sty.overline5)}
                >
                  <div
                    data-plasmic-name={"overline6"}
                    data-plasmic-override={overrides.overline6}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.overline6
                    )}
                  >
                    {"Afternoon"}
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"column1"}
                data-plasmic-override={overrides.column1}
                className={classNames(projectcss.all, sty.column1)}
              >
                <div
                  data-plasmic-name={"timeSelector16"}
                  data-plasmic-override={overrides.timeSelector16}
                  className={classNames(projectcss.all, sty.timeSelector16)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg16"}
                      data-plasmic-override={overrides.disabledBg16}
                      className={classNames(projectcss.all, sty.disabledBg16)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg16"}
                      data-plasmic-override={overrides.enabledBg16}
                      className={classNames(projectcss.all, sty.enabledBg16)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg16"}
                    data-plasmic-override={overrides.outlineBg16}
                    className={classNames(projectcss.all, sty.outlineBg16)}
                  />

                  <div
                    data-plasmic-name={"placeholder31"}
                    data-plasmic-override={overrides.placeholder31}
                    className={classNames(projectcss.all, sty.placeholder31)}
                  >
                    <div
                      data-plasmic-name={"placeholder32"}
                      data-plasmic-override={overrides.placeholder32}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder32
                      )}
                    >
                      {"11:00 AM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector17"}
                  data-plasmic-override={overrides.timeSelector17}
                  className={classNames(projectcss.all, sty.timeSelector17)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg17"}
                      data-plasmic-override={overrides.disabledBg17}
                      className={classNames(projectcss.all, sty.disabledBg17)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg17"}
                      data-plasmic-override={overrides.enabledBg17}
                      className={classNames(projectcss.all, sty.enabledBg17)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg17"}
                    data-plasmic-override={overrides.outlineBg17}
                    className={classNames(projectcss.all, sty.outlineBg17)}
                  />

                  <div
                    data-plasmic-name={"placeholder33"}
                    data-plasmic-override={overrides.placeholder33}
                    className={classNames(projectcss.all, sty.placeholder33)}
                  >
                    <div
                      data-plasmic-name={"placeholder34"}
                      data-plasmic-override={overrides.placeholder34}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder34
                      )}
                    >
                      {"10:00 AM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector18"}
                  data-plasmic-override={overrides.timeSelector18}
                  className={classNames(projectcss.all, sty.timeSelector18)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg18"}
                      data-plasmic-override={overrides.disabledBg18}
                      className={classNames(projectcss.all, sty.disabledBg18)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg18"}
                      data-plasmic-override={overrides.enabledBg18}
                      className={classNames(projectcss.all, sty.enabledBg18)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg18"}
                    data-plasmic-override={overrides.outlineBg18}
                    className={classNames(projectcss.all, sty.outlineBg18)}
                  />

                  <div
                    data-plasmic-name={"placeholder35"}
                    data-plasmic-override={overrides.placeholder35}
                    className={classNames(projectcss.all, sty.placeholder35)}
                  >
                    <div
                      data-plasmic-name={"placeholder36"}
                      data-plasmic-override={overrides.placeholder36}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder36
                      )}
                    >
                      {"8:00 AM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"timeSelector19"}
                  data-plasmic-override={overrides.timeSelector19}
                  className={classNames(projectcss.all, sty.timeSelector19)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"disabledBg19"}
                      data-plasmic-override={overrides.disabledBg19}
                      className={classNames(projectcss.all, sty.disabledBg19)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"enabledBg19"}
                      data-plasmic-override={overrides.enabledBg19}
                      className={classNames(projectcss.all, sty.enabledBg19)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"outlineBg19"}
                    data-plasmic-override={overrides.outlineBg19}
                    className={classNames(projectcss.all, sty.outlineBg19)}
                  />

                  <div
                    data-plasmic-name={"placeholder37"}
                    data-plasmic-override={overrides.placeholder37}
                    className={classNames(projectcss.all, sty.placeholder37)}
                  >
                    <div
                      data-plasmic-name={"placeholder38"}
                      data-plasmic-override={overrides.placeholder38}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.placeholder38
                      )}
                    >
                      {"7:00 AM"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"overline7"}
                  data-plasmic-override={overrides.overline7}
                  className={classNames(projectcss.all, sty.overline7)}
                >
                  <div
                    data-plasmic-name={"overline8"}
                    data-plasmic-override={overrides.overline8}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.overline8
                    )}
                  >
                    {"Morning"}
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"timeSelector20"}
                data-plasmic-override={overrides.timeSelector20}
                className={classNames(projectcss.all, sty.timeSelector20)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"disabledBg20"}
                    data-plasmic-override={overrides.disabledBg20}
                    className={classNames(projectcss.all, sty.disabledBg20)}
                  />
                ) : null}
                {false ? (
                  <div
                    data-plasmic-name={"enabledBg20"}
                    data-plasmic-override={overrides.enabledBg20}
                    className={classNames(projectcss.all, sty.enabledBg20)}
                  />
                ) : null}
                <div
                  data-plasmic-name={"outlineBg20"}
                  data-plasmic-override={overrides.outlineBg20}
                  className={classNames(projectcss.all, sty.outlineBg20)}
                />

                <div
                  data-plasmic-name={"placeholder39"}
                  data-plasmic-override={overrides.placeholder39}
                  className={classNames(projectcss.all, sty.placeholder39)}
                >
                  <div
                    data-plasmic-name={"placeholder40"}
                    data-plasmic-override={overrides.placeholder40}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.placeholder40
                    )}
                  >
                    {"9:00 AM"}
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"subcaption"}
                data-plasmic-override={overrides.subcaption}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.subcaption
                )}
              >
                {"Alex has planned a session with his friends."}
              </div>
            </div>
            <div
              data-plasmic-name={"buttonOutlineXs"}
              data-plasmic-override={overrides.buttonOutlineXs}
              className={classNames(projectcss.all, sty.buttonOutlineXs)}
            >
              {false ? (
                <div
                  data-plasmic-name={"buttonBg"}
                  data-plasmic-override={overrides.buttonBg}
                  className={classNames(projectcss.all, sty.buttonBg)}
                />
              ) : null}
              <div
                data-plasmic-name={"caption"}
                data-plasmic-override={overrides.caption}
                className={classNames(projectcss.all, sty.caption)}
              >
                <div
                  data-plasmic-name={"caption2"}
                  data-plasmic-override={overrides.caption2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.caption2
                  )}
                >
                  {"2 May 2022"}
                </div>
              </div>
              <div
                data-plasmic-name={"left"}
                data-plasmic-override={overrides.left}
                className={classNames(projectcss.all, sty.left)}
              >
                {false ? (
                  <ArrowLeftIcon
                    className={classNames(projectcss.all, sty.svg__ict9)}
                    role={"img"}
                  />
                ) : null}
                <ChevronLeftIcon
                  className={classNames(projectcss.all, sty.svg__kpjZ5)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"right"}
                data-plasmic-override={overrides.right}
                className={classNames(projectcss.all, sty.right)}
              >
                {false ? (
                  <ArrowRight2Icon
                    className={classNames(projectcss.all, sty.svg__j1NFa)}
                    role={"img"}
                  />
                ) : null}
                <ChevronRightIcon
                  className={classNames(projectcss.all, sty.svg__hsivY)}
                  role={"img"}
                />
              </div>
            </div>
            <div
              data-plasmic-name={"smallHeading"}
              data-plasmic-override={overrides.smallHeading}
              className={classNames(projectcss.all, sty.smallHeading)}
            >
              {false ? (
                <div
                  data-plasmic-name={"subcaption2"}
                  data-plasmic-override={overrides.subcaption2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.subcaption2
                  )}
                >
                  {"Choose a time period to plan your task."}
                </div>
              ) : null}
              <div
                data-plasmic-name={"h6"}
                data-plasmic-override={overrides.h6}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.h6
                )}
              >
                {"Select a time interval"}
              </div>
            </div>
            <div
              data-plasmic-name={"subcaption3"}
              data-plasmic-override={overrides.subcaption3}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.subcaption3
              )}
            >
              {"Choose a time period to see available game session."}
            </div>
            <div
              data-plasmic-name={"h62"}
              data-plasmic-override={overrides.h62}
              className={classNames(projectcss.all, sty.h62)}
            >
              <div
                data-plasmic-name={"h63"}
                data-plasmic-override={overrides.h63}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.h63
                )}
              >
                {"Time Selector"}
              </div>
            </div>
            <div
              data-plasmic-name={"loginBtn"}
              data-plasmic-override={overrides.loginBtn}
              className={classNames(projectcss.all, sty.loginBtn)}
            >
              <div
                data-plasmic-name={"rectangle"}
                data-plasmic-override={overrides.rectangle}
                className={classNames(projectcss.all, sty.rectangle)}
              />

              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text
                )}
              >
                {"REQUEST"}
              </div>
            </div>
            <div
              data-plasmic-name={"h33"}
              data-plasmic-override={overrides.h33}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.h33
              )}
            >
              {"Your Calendar"}
            </div>
            <Vector2Icon
              className={classNames(projectcss.all, sty.svg___1Jym9)}
              role={"img"}
            />

            <VectorIcon
              className={classNames(projectcss.all, sty.svg__qgzo)}
              role={"img"}
            />

            <div
              data-plasmic-name={"buttonOutlineXs2"}
              data-plasmic-override={overrides.buttonOutlineXs2}
              className={classNames(projectcss.all, sty.buttonOutlineXs2)}
            >
              {false ? (
                <div
                  data-plasmic-name={"buttonBg2"}
                  data-plasmic-override={overrides.buttonBg2}
                  className={classNames(projectcss.all, sty.buttonBg2)}
                />
              ) : null}
              <div
                data-plasmic-name={"caption3"}
                data-plasmic-override={overrides.caption3}
                className={classNames(projectcss.all, sty.caption3)}
              >
                <div
                  data-plasmic-name={"caption4"}
                  data-plasmic-override={overrides.caption4}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.caption4
                  )}
                >
                  {"May 2022"}
                </div>
              </div>
              {false ? (
                <div
                  data-plasmic-name={"left2"}
                  data-plasmic-override={overrides.left2}
                  className={classNames(projectcss.all, sty.left2)}
                >
                  {false ? (
                    <ArrowLeftIcon
                      className={classNames(projectcss.all, sty.svg__gxzy1)}
                      role={"img"}
                    />
                  ) : null}
                  <ChevronLeftIcon
                    className={classNames(projectcss.all, sty.svg___7CP3D)}
                    role={"img"}
                  />
                </div>
              ) : null}
              {false ? (
                <div
                  data-plasmic-name={"right2"}
                  data-plasmic-override={overrides.right2}
                  className={classNames(projectcss.all, sty.right2)}
                >
                  {false ? (
                    <ArrowRight2Icon
                      className={classNames(projectcss.all, sty.svg__xbC9T)}
                      role={"img"}
                    />
                  ) : null}
                  {false ? (
                    <ChevronRightIcon
                      className={classNames(projectcss.all, sty.svg__t9Uct)}
                      role={"img"}
                    />
                  ) : null}
                </div>
              ) : null}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "calendarPage4",
    "cardBg",
    "selectorTable",
    "column4",
    "timeSelector",
    "disabledBg",
    "enabledBg",
    "outlineBg",
    "placeholder",
    "placeholder2",
    "timeSelector2",
    "disabledBg2",
    "enabledBg2",
    "outlineBg2",
    "placeholder3",
    "placeholder4",
    "timeSelector3",
    "disabledBg3",
    "enabledBg3",
    "outlineBg3",
    "placeholder5",
    "placeholder6",
    "timeSelector4",
    "disabledBg4",
    "enabledBg4",
    "outlineBg4",
    "placeholder7",
    "placeholder8",
    "timeSelector5",
    "disabledBg5",
    "enabledBg5",
    "outlineBg5",
    "placeholder9",
    "placeholder10",
    "overline",
    "overline2",
    "column3",
    "timeSelector6",
    "disabledBg6",
    "enabledBg6",
    "outlineBg6",
    "placeholder11",
    "placeholder12",
    "timeSelector7",
    "disabledBg7",
    "enabledBg7",
    "outlineBg7",
    "placeholder13",
    "placeholder14",
    "timeSelector8",
    "disabledBg8",
    "enabledBg8",
    "outlineBg8",
    "placeholder15",
    "placeholder16",
    "timeSelector9",
    "disabledBg9",
    "enabledBg9",
    "outlineBg9",
    "placeholder17",
    "placeholder18",
    "timeSelector10",
    "disabledBg10",
    "enabledBg10",
    "outlineBg10",
    "placeholder19",
    "placeholder20",
    "overline3",
    "overline4",
    "column2",
    "timeSelector11",
    "disabledBg11",
    "enabledBg11",
    "outlineBg11",
    "placeholder21",
    "placeholder22",
    "timeSelector12",
    "disabledBg12",
    "enabledBg12",
    "outlineBg12",
    "placeholder23",
    "placeholder24",
    "timeSelector13",
    "disabledBg13",
    "enabledBg13",
    "outlineBg13",
    "placeholder25",
    "placeholder26",
    "timeSelector14",
    "disabledBg14",
    "enabledBg14",
    "outlineBg14",
    "placeholder27",
    "placeholder28",
    "h3",
    "h32",
    "rectangle40",
    "avatarhumanmanprofileicon13200858767166282345",
    "timeSelector15",
    "disabledBg15",
    "enabledBg15",
    "outlineBg15",
    "placeholder29",
    "placeholder30",
    "overline5",
    "overline6",
    "column1",
    "timeSelector16",
    "disabledBg16",
    "enabledBg16",
    "outlineBg16",
    "placeholder31",
    "placeholder32",
    "timeSelector17",
    "disabledBg17",
    "enabledBg17",
    "outlineBg17",
    "placeholder33",
    "placeholder34",
    "timeSelector18",
    "disabledBg18",
    "enabledBg18",
    "outlineBg18",
    "placeholder35",
    "placeholder36",
    "timeSelector19",
    "disabledBg19",
    "enabledBg19",
    "outlineBg19",
    "placeholder37",
    "placeholder38",
    "overline7",
    "overline8",
    "timeSelector20",
    "disabledBg20",
    "enabledBg20",
    "outlineBg20",
    "placeholder39",
    "placeholder40",
    "subcaption",
    "buttonOutlineXs",
    "buttonBg",
    "caption",
    "caption2",
    "left",
    "right",
    "smallHeading",
    "subcaption2",
    "h6",
    "subcaption3",
    "h62",
    "h63",
    "loginBtn",
    "rectangle",
    "text",
    "h33",
    "buttonOutlineXs2",
    "buttonBg2",
    "caption3",
    "caption4",
    "left2",
    "right2"
  ],

  calendarPage4: [
    "calendarPage4",
    "cardBg",
    "selectorTable",
    "column4",
    "timeSelector",
    "disabledBg",
    "enabledBg",
    "outlineBg",
    "placeholder",
    "placeholder2",
    "timeSelector2",
    "disabledBg2",
    "enabledBg2",
    "outlineBg2",
    "placeholder3",
    "placeholder4",
    "timeSelector3",
    "disabledBg3",
    "enabledBg3",
    "outlineBg3",
    "placeholder5",
    "placeholder6",
    "timeSelector4",
    "disabledBg4",
    "enabledBg4",
    "outlineBg4",
    "placeholder7",
    "placeholder8",
    "timeSelector5",
    "disabledBg5",
    "enabledBg5",
    "outlineBg5",
    "placeholder9",
    "placeholder10",
    "overline",
    "overline2",
    "column3",
    "timeSelector6",
    "disabledBg6",
    "enabledBg6",
    "outlineBg6",
    "placeholder11",
    "placeholder12",
    "timeSelector7",
    "disabledBg7",
    "enabledBg7",
    "outlineBg7",
    "placeholder13",
    "placeholder14",
    "timeSelector8",
    "disabledBg8",
    "enabledBg8",
    "outlineBg8",
    "placeholder15",
    "placeholder16",
    "timeSelector9",
    "disabledBg9",
    "enabledBg9",
    "outlineBg9",
    "placeholder17",
    "placeholder18",
    "timeSelector10",
    "disabledBg10",
    "enabledBg10",
    "outlineBg10",
    "placeholder19",
    "placeholder20",
    "overline3",
    "overline4",
    "column2",
    "timeSelector11",
    "disabledBg11",
    "enabledBg11",
    "outlineBg11",
    "placeholder21",
    "placeholder22",
    "timeSelector12",
    "disabledBg12",
    "enabledBg12",
    "outlineBg12",
    "placeholder23",
    "placeholder24",
    "timeSelector13",
    "disabledBg13",
    "enabledBg13",
    "outlineBg13",
    "placeholder25",
    "placeholder26",
    "timeSelector14",
    "disabledBg14",
    "enabledBg14",
    "outlineBg14",
    "placeholder27",
    "placeholder28",
    "h3",
    "h32",
    "rectangle40",
    "avatarhumanmanprofileicon13200858767166282345",
    "timeSelector15",
    "disabledBg15",
    "enabledBg15",
    "outlineBg15",
    "placeholder29",
    "placeholder30",
    "overline5",
    "overline6",
    "column1",
    "timeSelector16",
    "disabledBg16",
    "enabledBg16",
    "outlineBg16",
    "placeholder31",
    "placeholder32",
    "timeSelector17",
    "disabledBg17",
    "enabledBg17",
    "outlineBg17",
    "placeholder33",
    "placeholder34",
    "timeSelector18",
    "disabledBg18",
    "enabledBg18",
    "outlineBg18",
    "placeholder35",
    "placeholder36",
    "timeSelector19",
    "disabledBg19",
    "enabledBg19",
    "outlineBg19",
    "placeholder37",
    "placeholder38",
    "overline7",
    "overline8",
    "timeSelector20",
    "disabledBg20",
    "enabledBg20",
    "outlineBg20",
    "placeholder39",
    "placeholder40",
    "subcaption",
    "buttonOutlineXs",
    "buttonBg",
    "caption",
    "caption2",
    "left",
    "right",
    "smallHeading",
    "subcaption2",
    "h6",
    "subcaption3",
    "h62",
    "h63",
    "loginBtn",
    "rectangle",
    "text",
    "h33",
    "buttonOutlineXs2",
    "buttonBg2",
    "caption3",
    "caption4",
    "left2",
    "right2"
  ],

  cardBg: ["cardBg"],
  selectorTable: [
    "selectorTable",
    "column4",
    "timeSelector",
    "disabledBg",
    "enabledBg",
    "outlineBg",
    "placeholder",
    "placeholder2",
    "timeSelector2",
    "disabledBg2",
    "enabledBg2",
    "outlineBg2",
    "placeholder3",
    "placeholder4",
    "timeSelector3",
    "disabledBg3",
    "enabledBg3",
    "outlineBg3",
    "placeholder5",
    "placeholder6",
    "timeSelector4",
    "disabledBg4",
    "enabledBg4",
    "outlineBg4",
    "placeholder7",
    "placeholder8",
    "timeSelector5",
    "disabledBg5",
    "enabledBg5",
    "outlineBg5",
    "placeholder9",
    "placeholder10",
    "overline",
    "overline2",
    "column3",
    "timeSelector6",
    "disabledBg6",
    "enabledBg6",
    "outlineBg6",
    "placeholder11",
    "placeholder12",
    "timeSelector7",
    "disabledBg7",
    "enabledBg7",
    "outlineBg7",
    "placeholder13",
    "placeholder14",
    "timeSelector8",
    "disabledBg8",
    "enabledBg8",
    "outlineBg8",
    "placeholder15",
    "placeholder16",
    "timeSelector9",
    "disabledBg9",
    "enabledBg9",
    "outlineBg9",
    "placeholder17",
    "placeholder18",
    "timeSelector10",
    "disabledBg10",
    "enabledBg10",
    "outlineBg10",
    "placeholder19",
    "placeholder20",
    "overline3",
    "overline4",
    "column2",
    "timeSelector11",
    "disabledBg11",
    "enabledBg11",
    "outlineBg11",
    "placeholder21",
    "placeholder22",
    "timeSelector12",
    "disabledBg12",
    "enabledBg12",
    "outlineBg12",
    "placeholder23",
    "placeholder24",
    "timeSelector13",
    "disabledBg13",
    "enabledBg13",
    "outlineBg13",
    "placeholder25",
    "placeholder26",
    "timeSelector14",
    "disabledBg14",
    "enabledBg14",
    "outlineBg14",
    "placeholder27",
    "placeholder28",
    "h3",
    "h32",
    "rectangle40",
    "avatarhumanmanprofileicon13200858767166282345",
    "timeSelector15",
    "disabledBg15",
    "enabledBg15",
    "outlineBg15",
    "placeholder29",
    "placeholder30",
    "overline5",
    "overline6",
    "column1",
    "timeSelector16",
    "disabledBg16",
    "enabledBg16",
    "outlineBg16",
    "placeholder31",
    "placeholder32",
    "timeSelector17",
    "disabledBg17",
    "enabledBg17",
    "outlineBg17",
    "placeholder33",
    "placeholder34",
    "timeSelector18",
    "disabledBg18",
    "enabledBg18",
    "outlineBg18",
    "placeholder35",
    "placeholder36",
    "timeSelector19",
    "disabledBg19",
    "enabledBg19",
    "outlineBg19",
    "placeholder37",
    "placeholder38",
    "overline7",
    "overline8",
    "timeSelector20",
    "disabledBg20",
    "enabledBg20",
    "outlineBg20",
    "placeholder39",
    "placeholder40",
    "subcaption"
  ],

  column4: [
    "column4",
    "timeSelector",
    "disabledBg",
    "enabledBg",
    "outlineBg",
    "placeholder",
    "placeholder2",
    "timeSelector2",
    "disabledBg2",
    "enabledBg2",
    "outlineBg2",
    "placeholder3",
    "placeholder4",
    "timeSelector3",
    "disabledBg3",
    "enabledBg3",
    "outlineBg3",
    "placeholder5",
    "placeholder6",
    "timeSelector4",
    "disabledBg4",
    "enabledBg4",
    "outlineBg4",
    "placeholder7",
    "placeholder8",
    "timeSelector5",
    "disabledBg5",
    "enabledBg5",
    "outlineBg5",
    "placeholder9",
    "placeholder10",
    "overline",
    "overline2"
  ],

  timeSelector: [
    "timeSelector",
    "disabledBg",
    "enabledBg",
    "outlineBg",
    "placeholder",
    "placeholder2"
  ],

  disabledBg: ["disabledBg"],
  enabledBg: ["enabledBg"],
  outlineBg: ["outlineBg"],
  placeholder: ["placeholder", "placeholder2"],
  placeholder2: ["placeholder2"],
  timeSelector2: [
    "timeSelector2",
    "disabledBg2",
    "enabledBg2",
    "outlineBg2",
    "placeholder3",
    "placeholder4"
  ],

  disabledBg2: ["disabledBg2"],
  enabledBg2: ["enabledBg2"],
  outlineBg2: ["outlineBg2"],
  placeholder3: ["placeholder3", "placeholder4"],
  placeholder4: ["placeholder4"],
  timeSelector3: [
    "timeSelector3",
    "disabledBg3",
    "enabledBg3",
    "outlineBg3",
    "placeholder5",
    "placeholder6"
  ],

  disabledBg3: ["disabledBg3"],
  enabledBg3: ["enabledBg3"],
  outlineBg3: ["outlineBg3"],
  placeholder5: ["placeholder5", "placeholder6"],
  placeholder6: ["placeholder6"],
  timeSelector4: [
    "timeSelector4",
    "disabledBg4",
    "enabledBg4",
    "outlineBg4",
    "placeholder7",
    "placeholder8"
  ],

  disabledBg4: ["disabledBg4"],
  enabledBg4: ["enabledBg4"],
  outlineBg4: ["outlineBg4"],
  placeholder7: ["placeholder7", "placeholder8"],
  placeholder8: ["placeholder8"],
  timeSelector5: [
    "timeSelector5",
    "disabledBg5",
    "enabledBg5",
    "outlineBg5",
    "placeholder9",
    "placeholder10"
  ],

  disabledBg5: ["disabledBg5"],
  enabledBg5: ["enabledBg5"],
  outlineBg5: ["outlineBg5"],
  placeholder9: ["placeholder9", "placeholder10"],
  placeholder10: ["placeholder10"],
  overline: ["overline", "overline2"],
  overline2: ["overline2"],
  column3: [
    "column3",
    "timeSelector6",
    "disabledBg6",
    "enabledBg6",
    "outlineBg6",
    "placeholder11",
    "placeholder12",
    "timeSelector7",
    "disabledBg7",
    "enabledBg7",
    "outlineBg7",
    "placeholder13",
    "placeholder14",
    "timeSelector8",
    "disabledBg8",
    "enabledBg8",
    "outlineBg8",
    "placeholder15",
    "placeholder16",
    "timeSelector9",
    "disabledBg9",
    "enabledBg9",
    "outlineBg9",
    "placeholder17",
    "placeholder18",
    "timeSelector10",
    "disabledBg10",
    "enabledBg10",
    "outlineBg10",
    "placeholder19",
    "placeholder20",
    "overline3",
    "overline4"
  ],

  timeSelector6: [
    "timeSelector6",
    "disabledBg6",
    "enabledBg6",
    "outlineBg6",
    "placeholder11",
    "placeholder12"
  ],

  disabledBg6: ["disabledBg6"],
  enabledBg6: ["enabledBg6"],
  outlineBg6: ["outlineBg6"],
  placeholder11: ["placeholder11", "placeholder12"],
  placeholder12: ["placeholder12"],
  timeSelector7: [
    "timeSelector7",
    "disabledBg7",
    "enabledBg7",
    "outlineBg7",
    "placeholder13",
    "placeholder14"
  ],

  disabledBg7: ["disabledBg7"],
  enabledBg7: ["enabledBg7"],
  outlineBg7: ["outlineBg7"],
  placeholder13: ["placeholder13", "placeholder14"],
  placeholder14: ["placeholder14"],
  timeSelector8: [
    "timeSelector8",
    "disabledBg8",
    "enabledBg8",
    "outlineBg8",
    "placeholder15",
    "placeholder16"
  ],

  disabledBg8: ["disabledBg8"],
  enabledBg8: ["enabledBg8"],
  outlineBg8: ["outlineBg8"],
  placeholder15: ["placeholder15", "placeholder16"],
  placeholder16: ["placeholder16"],
  timeSelector9: [
    "timeSelector9",
    "disabledBg9",
    "enabledBg9",
    "outlineBg9",
    "placeholder17",
    "placeholder18"
  ],

  disabledBg9: ["disabledBg9"],
  enabledBg9: ["enabledBg9"],
  outlineBg9: ["outlineBg9"],
  placeholder17: ["placeholder17", "placeholder18"],
  placeholder18: ["placeholder18"],
  timeSelector10: [
    "timeSelector10",
    "disabledBg10",
    "enabledBg10",
    "outlineBg10",
    "placeholder19",
    "placeholder20"
  ],

  disabledBg10: ["disabledBg10"],
  enabledBg10: ["enabledBg10"],
  outlineBg10: ["outlineBg10"],
  placeholder19: ["placeholder19", "placeholder20"],
  placeholder20: ["placeholder20"],
  overline3: ["overline3", "overline4"],
  overline4: ["overline4"],
  column2: [
    "column2",
    "timeSelector11",
    "disabledBg11",
    "enabledBg11",
    "outlineBg11",
    "placeholder21",
    "placeholder22",
    "timeSelector12",
    "disabledBg12",
    "enabledBg12",
    "outlineBg12",
    "placeholder23",
    "placeholder24",
    "timeSelector13",
    "disabledBg13",
    "enabledBg13",
    "outlineBg13",
    "placeholder25",
    "placeholder26",
    "timeSelector14",
    "disabledBg14",
    "enabledBg14",
    "outlineBg14",
    "placeholder27",
    "placeholder28",
    "h3",
    "h32",
    "rectangle40",
    "avatarhumanmanprofileicon13200858767166282345",
    "timeSelector15",
    "disabledBg15",
    "enabledBg15",
    "outlineBg15",
    "placeholder29",
    "placeholder30",
    "overline5",
    "overline6"
  ],

  timeSelector11: [
    "timeSelector11",
    "disabledBg11",
    "enabledBg11",
    "outlineBg11",
    "placeholder21",
    "placeholder22"
  ],

  disabledBg11: ["disabledBg11"],
  enabledBg11: ["enabledBg11"],
  outlineBg11: ["outlineBg11"],
  placeholder21: ["placeholder21", "placeholder22"],
  placeholder22: ["placeholder22"],
  timeSelector12: [
    "timeSelector12",
    "disabledBg12",
    "enabledBg12",
    "outlineBg12",
    "placeholder23",
    "placeholder24"
  ],

  disabledBg12: ["disabledBg12"],
  enabledBg12: ["enabledBg12"],
  outlineBg12: ["outlineBg12"],
  placeholder23: ["placeholder23", "placeholder24"],
  placeholder24: ["placeholder24"],
  timeSelector13: [
    "timeSelector13",
    "disabledBg13",
    "enabledBg13",
    "outlineBg13",
    "placeholder25",
    "placeholder26"
  ],

  disabledBg13: ["disabledBg13"],
  enabledBg13: ["enabledBg13"],
  outlineBg13: ["outlineBg13"],
  placeholder25: ["placeholder25", "placeholder26"],
  placeholder26: ["placeholder26"],
  timeSelector14: [
    "timeSelector14",
    "disabledBg14",
    "enabledBg14",
    "outlineBg14",
    "placeholder27",
    "placeholder28",
    "h3",
    "h32",
    "rectangle40",
    "avatarhumanmanprofileicon13200858767166282345"
  ],

  disabledBg14: ["disabledBg14"],
  enabledBg14: ["enabledBg14"],
  outlineBg14: ["outlineBg14"],
  placeholder27: ["placeholder27", "placeholder28"],
  placeholder28: ["placeholder28"],
  h3: ["h3", "h32"],
  h32: ["h32"],
  rectangle40: ["rectangle40"],
  avatarhumanmanprofileicon13200858767166282345: [
    "avatarhumanmanprofileicon13200858767166282345"
  ],

  timeSelector15: [
    "timeSelector15",
    "disabledBg15",
    "enabledBg15",
    "outlineBg15",
    "placeholder29",
    "placeholder30"
  ],

  disabledBg15: ["disabledBg15"],
  enabledBg15: ["enabledBg15"],
  outlineBg15: ["outlineBg15"],
  placeholder29: ["placeholder29", "placeholder30"],
  placeholder30: ["placeholder30"],
  overline5: ["overline5", "overline6"],
  overline6: ["overline6"],
  column1: [
    "column1",
    "timeSelector16",
    "disabledBg16",
    "enabledBg16",
    "outlineBg16",
    "placeholder31",
    "placeholder32",
    "timeSelector17",
    "disabledBg17",
    "enabledBg17",
    "outlineBg17",
    "placeholder33",
    "placeholder34",
    "timeSelector18",
    "disabledBg18",
    "enabledBg18",
    "outlineBg18",
    "placeholder35",
    "placeholder36",
    "timeSelector19",
    "disabledBg19",
    "enabledBg19",
    "outlineBg19",
    "placeholder37",
    "placeholder38",
    "overline7",
    "overline8"
  ],

  timeSelector16: [
    "timeSelector16",
    "disabledBg16",
    "enabledBg16",
    "outlineBg16",
    "placeholder31",
    "placeholder32"
  ],

  disabledBg16: ["disabledBg16"],
  enabledBg16: ["enabledBg16"],
  outlineBg16: ["outlineBg16"],
  placeholder31: ["placeholder31", "placeholder32"],
  placeholder32: ["placeholder32"],
  timeSelector17: [
    "timeSelector17",
    "disabledBg17",
    "enabledBg17",
    "outlineBg17",
    "placeholder33",
    "placeholder34"
  ],

  disabledBg17: ["disabledBg17"],
  enabledBg17: ["enabledBg17"],
  outlineBg17: ["outlineBg17"],
  placeholder33: ["placeholder33", "placeholder34"],
  placeholder34: ["placeholder34"],
  timeSelector18: [
    "timeSelector18",
    "disabledBg18",
    "enabledBg18",
    "outlineBg18",
    "placeholder35",
    "placeholder36"
  ],

  disabledBg18: ["disabledBg18"],
  enabledBg18: ["enabledBg18"],
  outlineBg18: ["outlineBg18"],
  placeholder35: ["placeholder35", "placeholder36"],
  placeholder36: ["placeholder36"],
  timeSelector19: [
    "timeSelector19",
    "disabledBg19",
    "enabledBg19",
    "outlineBg19",
    "placeholder37",
    "placeholder38"
  ],

  disabledBg19: ["disabledBg19"],
  enabledBg19: ["enabledBg19"],
  outlineBg19: ["outlineBg19"],
  placeholder37: ["placeholder37", "placeholder38"],
  placeholder38: ["placeholder38"],
  overline7: ["overline7", "overline8"],
  overline8: ["overline8"],
  timeSelector20: [
    "timeSelector20",
    "disabledBg20",
    "enabledBg20",
    "outlineBg20",
    "placeholder39",
    "placeholder40"
  ],

  disabledBg20: ["disabledBg20"],
  enabledBg20: ["enabledBg20"],
  outlineBg20: ["outlineBg20"],
  placeholder39: ["placeholder39", "placeholder40"],
  placeholder40: ["placeholder40"],
  subcaption: ["subcaption"],
  buttonOutlineXs: [
    "buttonOutlineXs",
    "buttonBg",
    "caption",
    "caption2",
    "left",
    "right"
  ],

  buttonBg: ["buttonBg"],
  caption: ["caption", "caption2"],
  caption2: ["caption2"],
  left: ["left"],
  right: ["right"],
  smallHeading: ["smallHeading", "subcaption2", "h6"],
  subcaption2: ["subcaption2"],
  h6: ["h6"],
  subcaption3: ["subcaption3"],
  h62: ["h62", "h63"],
  h63: ["h63"],
  loginBtn: ["loginBtn", "rectangle", "text"],
  rectangle: ["rectangle"],
  text: ["text"],
  h33: ["h33"],
  buttonOutlineXs2: [
    "buttonOutlineXs2",
    "buttonBg2",
    "caption3",
    "caption4",
    "left2",
    "right2"
  ],

  buttonBg2: ["buttonBg2"],
  caption3: ["caption3", "caption4"],
  caption4: ["caption4"],
  left2: ["left2"],
  right2: ["right2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCalendarPage4__ArgProps,
          internalVariantPropNames: PlasmicCalendarPage4__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCalendarPage4__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCalendarPage4";
  } else {
    func.displayName = `PlasmicCalendarPage4.${nodeName}`;
  }
  return func;
}

export const PlasmicCalendarPage4 = Object.assign(
  // Top-level PlasmicCalendarPage4 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    calendarPage4: makeNodeComponent("calendarPage4"),
    cardBg: makeNodeComponent("cardBg"),
    selectorTable: makeNodeComponent("selectorTable"),
    column4: makeNodeComponent("column4"),
    timeSelector: makeNodeComponent("timeSelector"),
    disabledBg: makeNodeComponent("disabledBg"),
    enabledBg: makeNodeComponent("enabledBg"),
    outlineBg: makeNodeComponent("outlineBg"),
    placeholder: makeNodeComponent("placeholder"),
    placeholder2: makeNodeComponent("placeholder2"),
    timeSelector2: makeNodeComponent("timeSelector2"),
    disabledBg2: makeNodeComponent("disabledBg2"),
    enabledBg2: makeNodeComponent("enabledBg2"),
    outlineBg2: makeNodeComponent("outlineBg2"),
    placeholder3: makeNodeComponent("placeholder3"),
    placeholder4: makeNodeComponent("placeholder4"),
    timeSelector3: makeNodeComponent("timeSelector3"),
    disabledBg3: makeNodeComponent("disabledBg3"),
    enabledBg3: makeNodeComponent("enabledBg3"),
    outlineBg3: makeNodeComponent("outlineBg3"),
    placeholder5: makeNodeComponent("placeholder5"),
    placeholder6: makeNodeComponent("placeholder6"),
    timeSelector4: makeNodeComponent("timeSelector4"),
    disabledBg4: makeNodeComponent("disabledBg4"),
    enabledBg4: makeNodeComponent("enabledBg4"),
    outlineBg4: makeNodeComponent("outlineBg4"),
    placeholder7: makeNodeComponent("placeholder7"),
    placeholder8: makeNodeComponent("placeholder8"),
    timeSelector5: makeNodeComponent("timeSelector5"),
    disabledBg5: makeNodeComponent("disabledBg5"),
    enabledBg5: makeNodeComponent("enabledBg5"),
    outlineBg5: makeNodeComponent("outlineBg5"),
    placeholder9: makeNodeComponent("placeholder9"),
    placeholder10: makeNodeComponent("placeholder10"),
    overline: makeNodeComponent("overline"),
    overline2: makeNodeComponent("overline2"),
    column3: makeNodeComponent("column3"),
    timeSelector6: makeNodeComponent("timeSelector6"),
    disabledBg6: makeNodeComponent("disabledBg6"),
    enabledBg6: makeNodeComponent("enabledBg6"),
    outlineBg6: makeNodeComponent("outlineBg6"),
    placeholder11: makeNodeComponent("placeholder11"),
    placeholder12: makeNodeComponent("placeholder12"),
    timeSelector7: makeNodeComponent("timeSelector7"),
    disabledBg7: makeNodeComponent("disabledBg7"),
    enabledBg7: makeNodeComponent("enabledBg7"),
    outlineBg7: makeNodeComponent("outlineBg7"),
    placeholder13: makeNodeComponent("placeholder13"),
    placeholder14: makeNodeComponent("placeholder14"),
    timeSelector8: makeNodeComponent("timeSelector8"),
    disabledBg8: makeNodeComponent("disabledBg8"),
    enabledBg8: makeNodeComponent("enabledBg8"),
    outlineBg8: makeNodeComponent("outlineBg8"),
    placeholder15: makeNodeComponent("placeholder15"),
    placeholder16: makeNodeComponent("placeholder16"),
    timeSelector9: makeNodeComponent("timeSelector9"),
    disabledBg9: makeNodeComponent("disabledBg9"),
    enabledBg9: makeNodeComponent("enabledBg9"),
    outlineBg9: makeNodeComponent("outlineBg9"),
    placeholder17: makeNodeComponent("placeholder17"),
    placeholder18: makeNodeComponent("placeholder18"),
    timeSelector10: makeNodeComponent("timeSelector10"),
    disabledBg10: makeNodeComponent("disabledBg10"),
    enabledBg10: makeNodeComponent("enabledBg10"),
    outlineBg10: makeNodeComponent("outlineBg10"),
    placeholder19: makeNodeComponent("placeholder19"),
    placeholder20: makeNodeComponent("placeholder20"),
    overline3: makeNodeComponent("overline3"),
    overline4: makeNodeComponent("overline4"),
    column2: makeNodeComponent("column2"),
    timeSelector11: makeNodeComponent("timeSelector11"),
    disabledBg11: makeNodeComponent("disabledBg11"),
    enabledBg11: makeNodeComponent("enabledBg11"),
    outlineBg11: makeNodeComponent("outlineBg11"),
    placeholder21: makeNodeComponent("placeholder21"),
    placeholder22: makeNodeComponent("placeholder22"),
    timeSelector12: makeNodeComponent("timeSelector12"),
    disabledBg12: makeNodeComponent("disabledBg12"),
    enabledBg12: makeNodeComponent("enabledBg12"),
    outlineBg12: makeNodeComponent("outlineBg12"),
    placeholder23: makeNodeComponent("placeholder23"),
    placeholder24: makeNodeComponent("placeholder24"),
    timeSelector13: makeNodeComponent("timeSelector13"),
    disabledBg13: makeNodeComponent("disabledBg13"),
    enabledBg13: makeNodeComponent("enabledBg13"),
    outlineBg13: makeNodeComponent("outlineBg13"),
    placeholder25: makeNodeComponent("placeholder25"),
    placeholder26: makeNodeComponent("placeholder26"),
    timeSelector14: makeNodeComponent("timeSelector14"),
    disabledBg14: makeNodeComponent("disabledBg14"),
    enabledBg14: makeNodeComponent("enabledBg14"),
    outlineBg14: makeNodeComponent("outlineBg14"),
    placeholder27: makeNodeComponent("placeholder27"),
    placeholder28: makeNodeComponent("placeholder28"),
    h3: makeNodeComponent("h3"),
    h32: makeNodeComponent("h32"),
    rectangle40: makeNodeComponent("rectangle40"),
    avatarhumanmanprofileicon13200858767166282345: makeNodeComponent(
      "avatarhumanmanprofileicon13200858767166282345"
    ),
    timeSelector15: makeNodeComponent("timeSelector15"),
    disabledBg15: makeNodeComponent("disabledBg15"),
    enabledBg15: makeNodeComponent("enabledBg15"),
    outlineBg15: makeNodeComponent("outlineBg15"),
    placeholder29: makeNodeComponent("placeholder29"),
    placeholder30: makeNodeComponent("placeholder30"),
    overline5: makeNodeComponent("overline5"),
    overline6: makeNodeComponent("overline6"),
    column1: makeNodeComponent("column1"),
    timeSelector16: makeNodeComponent("timeSelector16"),
    disabledBg16: makeNodeComponent("disabledBg16"),
    enabledBg16: makeNodeComponent("enabledBg16"),
    outlineBg16: makeNodeComponent("outlineBg16"),
    placeholder31: makeNodeComponent("placeholder31"),
    placeholder32: makeNodeComponent("placeholder32"),
    timeSelector17: makeNodeComponent("timeSelector17"),
    disabledBg17: makeNodeComponent("disabledBg17"),
    enabledBg17: makeNodeComponent("enabledBg17"),
    outlineBg17: makeNodeComponent("outlineBg17"),
    placeholder33: makeNodeComponent("placeholder33"),
    placeholder34: makeNodeComponent("placeholder34"),
    timeSelector18: makeNodeComponent("timeSelector18"),
    disabledBg18: makeNodeComponent("disabledBg18"),
    enabledBg18: makeNodeComponent("enabledBg18"),
    outlineBg18: makeNodeComponent("outlineBg18"),
    placeholder35: makeNodeComponent("placeholder35"),
    placeholder36: makeNodeComponent("placeholder36"),
    timeSelector19: makeNodeComponent("timeSelector19"),
    disabledBg19: makeNodeComponent("disabledBg19"),
    enabledBg19: makeNodeComponent("enabledBg19"),
    outlineBg19: makeNodeComponent("outlineBg19"),
    placeholder37: makeNodeComponent("placeholder37"),
    placeholder38: makeNodeComponent("placeholder38"),
    overline7: makeNodeComponent("overline7"),
    overline8: makeNodeComponent("overline8"),
    timeSelector20: makeNodeComponent("timeSelector20"),
    disabledBg20: makeNodeComponent("disabledBg20"),
    enabledBg20: makeNodeComponent("enabledBg20"),
    outlineBg20: makeNodeComponent("outlineBg20"),
    placeholder39: makeNodeComponent("placeholder39"),
    placeholder40: makeNodeComponent("placeholder40"),
    subcaption: makeNodeComponent("subcaption"),
    buttonOutlineXs: makeNodeComponent("buttonOutlineXs"),
    buttonBg: makeNodeComponent("buttonBg"),
    caption: makeNodeComponent("caption"),
    caption2: makeNodeComponent("caption2"),
    left: makeNodeComponent("left"),
    right: makeNodeComponent("right"),
    smallHeading: makeNodeComponent("smallHeading"),
    subcaption2: makeNodeComponent("subcaption2"),
    h6: makeNodeComponent("h6"),
    subcaption3: makeNodeComponent("subcaption3"),
    h62: makeNodeComponent("h62"),
    h63: makeNodeComponent("h63"),
    loginBtn: makeNodeComponent("loginBtn"),
    rectangle: makeNodeComponent("rectangle"),
    text: makeNodeComponent("text"),
    h33: makeNodeComponent("h33"),
    buttonOutlineXs2: makeNodeComponent("buttonOutlineXs2"),
    buttonBg2: makeNodeComponent("buttonBg2"),
    caption3: makeNodeComponent("caption3"),
    caption4: makeNodeComponent("caption4"),
    left2: makeNodeComponent("left2"),
    right2: makeNodeComponent("right2"),
    // Metadata about props expected for PlasmicCalendarPage4
    internalVariantProps: PlasmicCalendarPage4__VariantProps,
    internalArgProps: PlasmicCalendarPage4__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCalendarPage4;
/* prettier-ignore-end */
