// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ivhpgazgw15hPKwKsPQEWr
// Component: ewY5BH5W9Z
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_game_schedule.module.css"; // plasmic-import: ivhpgazgw15hPKwKsPQEWr/projectcss
import sty from "./PlasmicHomePage.module.css"; // plasmic-import: ewY5BH5W9Z/css
import Ellipse19Icon from "./icons/PlasmicIcon__Ellipse19"; // plasmic-import: O2uVwEpw6T/icon
import Vector1StrokeIcon from "./icons/PlasmicIcon__Vector1Stroke"; // plasmic-import: dd_eaW0X0s/icon
import SocialIcon from "./icons/PlasmicIcon__Social"; // plasmic-import: 30NfKzi4H_/icon
import Vector1Stroke4Icon from "./icons/PlasmicIcon__Vector1Stroke4"; // plasmic-import: DzqyvHh9hmS/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: F4m3gz-3un/icon
import Ellipse20Icon from "./icons/PlasmicIcon__Ellipse20"; // plasmic-import: DkmZYFSkDH/icon
import rectangle5OyZckIra7C from "./images/rectangle5.svg"; // plasmic-import: OyZCKIra7c/picture

export const PlasmicHomePage__VariantProps = new Array();

export const PlasmicHomePage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHomePage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"homePage"}
            data-plasmic-override={overrides.homePage}
            className={classNames(projectcss.all, sty.homePage)}
          >
            <div
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames(projectcss.all, sty.section)}
            >
              <div
                data-plasmic-name={"background"}
                data-plasmic-override={overrides.background}
                className={classNames(projectcss.all, sty.background)}
              >
                <div
                  data-plasmic-name={"rectangle4"}
                  data-plasmic-override={overrides.rectangle4}
                  className={classNames(projectcss.all, sty.rectangle4)}
                />
              </div>
              <div
                data-plasmic-name={"image"}
                data-plasmic-override={overrides.image}
                className={classNames(projectcss.all, sty.image)}
              >
                <Ellipse19Icon
                  className={classNames(projectcss.all, sty.svg__fq98N)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"card"}
                  data-plasmic-override={overrides.card}
                  className={classNames(projectcss.all, sty.card)}
                >
                  <div
                    data-plasmic-name={"rectangle5"}
                    data-plasmic-override={overrides.rectangle5}
                    className={classNames(projectcss.all, sty.rectangle5)}
                  />

                  {false ? (
                    <div
                      data-plasmic-name={"group8"}
                      data-plasmic-override={overrides.group8}
                      className={classNames(projectcss.all, sty.group8)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2DcS0
                        )}
                      >
                        {"Purple Man"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kyYxz
                        )}
                      >
                        {"Gloop Series"}
                      </div>
                      <div
                        data-plasmic-name={"_12983"}
                        data-plasmic-override={overrides._12983}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty._12983
                        )}
                      >
                        {"#1094"}
                      </div>
                    </div>
                  ) : null}
                  {false ? (
                    <p.PlasmicImg
                      data-plasmic-name={"img"}
                      data-plasmic-override={overrides.img}
                      alt={""}
                      className={classNames(sty.img)}
                      displayHeight={"142px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"446px"}
                      loading={"lazy"}
                      src={{
                        src: rectangle5OyZckIra7C,
                        fullWidth: 446,
                        fullHeight: 142,
                        aspectRatio: 3.140845
                      }}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"group7"}
                      data-plasmic-override={overrides.group7}
                      className={classNames(projectcss.all, sty.group7)}
                    >
                      <div
                        data-plasmic-name={"_299Eth"}
                        data-plasmic-override={overrides._299Eth}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty._299Eth
                        )}
                      >
                        {"3.95 ETH"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nEy0Q
                        )}
                      >
                        {"Top bid"}
                      </div>
                      <div
                        data-plasmic-name={"_1DayLeft"}
                        data-plasmic-override={overrides._1DayLeft}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty._1DayLeft
                        )}
                      >
                        {"2 days left"}
                      </div>
                      <div
                        data-plasmic-name={"image2"}
                        data-plasmic-override={overrides.image2}
                        className={classNames(projectcss.all, sty.image2)}
                      />
                    </div>
                  ) : null}
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__x0G82
                )}
              >
                {"14"}
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nLhDy
              )}
            >
              {"Your Upcoming Schedule"}
            </div>
            <p.Stack
              as={"a"}
              data-plasmic-name={"sectionSmall"}
              data-plasmic-override={overrides.sectionSmall}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.sectionSmall
              )}
              href={`/calendar-page-1`}
            >
              {false ? (
                <div
                  data-plasmic-name={"icon"}
                  data-plasmic-override={overrides.icon}
                  className={classNames(projectcss.all, sty.icon)}
                >
                  <div
                    data-plasmic-name={"image3"}
                    data-plasmic-override={overrides.image3}
                    className={classNames(projectcss.all, sty.image3)}
                  />
                </div>
              ) : null}
              <div className={classNames(projectcss.all, sty.freeBox___96AlG)}>
                <div
                  data-plasmic-name={"anNftLikeNoOther"}
                  data-plasmic-override={overrides.anNftLikeNoOther}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.anNftLikeNoOther
                  )}
                >
                  {"Manage your calendar"}
                </div>
                {false ? (
                  <div
                    data-plasmic-name={
                      "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft"
                    }
                    data-plasmic-override={
                      overrides.dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft
                    )}
                  >
                    {"Test"}
                  </div>
                ) : null}
              </div>
            </p.Stack>
            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <div
                data-plasmic-name={"bottom"}
                data-plasmic-override={overrides.bottom}
                className={classNames(projectcss.all, sty.bottom)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6MDa7
                  )}
                >
                  {"© Copyright 2022 GameSchedule"}
                </div>
              </div>
              <div
                data-plasmic-name={"right"}
                data-plasmic-override={overrides.right}
                className={classNames(projectcss.all, sty.right)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jDgSs
                  )}
                >
                  {"About\nTerms\nLegal"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tcoUo
                  )}
                >
                  {"Press\nSupport"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7YABt
                  )}
                >
                  {"Twitter\nInstagram"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mWiMf
                  )}
                >
                  {"About"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___22Kff
                  )}
                >
                  {"Contact"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3RaIn
                  )}
                >
                  {"Social"}
                </div>
              </div>
              <div
                data-plasmic-name={"left"}
                data-plasmic-override={overrides.left}
                className={classNames(projectcss.all, sty.left)}
              >
                <div
                  data-plasmic-name={"logo"}
                  data-plasmic-override={overrides.logo}
                  className={classNames(projectcss.all, sty.logo)}
                >
                  <Vector1StrokeIcon
                    className={classNames(projectcss.all, sty.svg__dXCb2)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"nftlanding"}
                    data-plasmic-override={overrides.nftlanding}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.nftlanding
                    )}
                  >
                    {"gameschedule"}
                  </div>
                </div>
                <SocialIcon
                  className={classNames(projectcss.all, sty.svg__j2RvP)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"divider"}
                data-plasmic-override={overrides.divider}
                className={classNames(projectcss.all, sty.divider)}
              >
                <div
                  data-plasmic-name={"rectangle9"}
                  data-plasmic-override={overrides.rectangle9}
                  className={classNames(projectcss.all, sty.rectangle9)}
                />
              </div>
            </div>
            <div
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(projectcss.all, sty.header)}
            >
              <div
                data-plasmic-name={"logo2"}
                data-plasmic-override={overrides.logo2}
                className={classNames(projectcss.all, sty.logo2)}
              >
                <Vector1Stroke4Icon
                  className={classNames(projectcss.all, sty.svg___7N6Sc)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"nftlanding2"}
                  data-plasmic-override={overrides.nftlanding2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.nftlanding2
                  )}
                >
                  {"gameschedule"}
                </div>
              </div>
              <p.Stack
                as={"div"}
                data-plasmic-name={"navigation"}
                data-plasmic-override={overrides.navigation}
                hasGap={true}
                className={classNames(projectcss.all, sty.navigation)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eCg7I
                  )}
                >
                  {"Welcome Back noobmaster69!"}
                </div>
              </p.Stack>
            </div>
            <a
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__a94BI
              )}
            >
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__m1Pi
                )}
              >
                <VectorIcon
                  className={classNames(projectcss.all, sty.svg__jmaRo)}
                  role={"img"}
                />
              </a>
            </a>
            <div
              data-plasmic-name={"h3"}
              data-plasmic-override={overrides.h3}
              className={classNames(projectcss.all, sty.h3)}
            >
              <div
                data-plasmic-name={"h32"}
                data-plasmic-override={overrides.h32}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.h32
                )}
              >
                {"Recent Games"}
              </div>
            </div>
            <div
              data-plasmic-name={"rectangle33"}
              data-plasmic-override={overrides.rectangle33}
              className={classNames(projectcss.all, sty.rectangle33)}
            />

            <div
              data-plasmic-name={"rectangle34"}
              data-plasmic-override={overrides.rectangle34}
              className={classNames(projectcss.all, sty.rectangle34)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__sC4Mf
              )}
            >
              {"LAST PLAYED"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__unem9
              )}
            >
              {"16 HOURS AGO"}
            </div>
            <div
              data-plasmic-name={"fifa22Cover2"}
              data-plasmic-override={overrides.fifa22Cover2}
              className={classNames(projectcss.all, sty.fifa22Cover2)}
            />

            <div
              data-plasmic-name={"battlefield2042CoverArt1"}
              data-plasmic-override={overrides.battlefield2042CoverArt1}
              className={classNames(
                projectcss.all,
                sty.battlefield2042CoverArt1
              )}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hvvFx
              )}
            >
              {"BATTLEFIELD 2042"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__yveOb
              )}
            >
              {"LAST PLAYED"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bB7Tc
              )}
            >
              {"16 HOURS AGO"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bgOgj
              )}
            >
              {"BATTLEFIELD 2042"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__r2NfI
              )}
            >
              {"MON"}
            </div>
            <div
              data-plasmic-name={"rectangle37"}
              data-plasmic-override={overrides.rectangle37}
              className={classNames(projectcss.all, sty.rectangle37)}
            />

            <div
              data-plasmic-name={"rectangle38"}
              data-plasmic-override={overrides.rectangle38}
              className={classNames(projectcss.all, sty.rectangle38)}
            />

            <div
              data-plasmic-name={"fifa22Cover4"}
              data-plasmic-override={overrides.fifa22Cover4}
              className={classNames(projectcss.all, sty.fifa22Cover4)}
            />

            <div
              data-plasmic-name={"rectangle35"}
              data-plasmic-override={overrides.rectangle35}
              className={classNames(projectcss.all, sty.rectangle35)}
            />

            <div
              data-plasmic-name={"rectangle36"}
              data-plasmic-override={overrides.rectangle36}
              className={classNames(projectcss.all, sty.rectangle36)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__giMMf
              )}
            >
              {"LAST PLAYED"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___0Nlwb
              )}
            >
              {"3 days ago"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nEcsS
              )}
            >
              {"dota 2"}
            </div>
            <div
              data-plasmic-name={"fifa22Cover3"}
              data-plasmic-override={overrides.fifa22Cover3}
              className={classNames(projectcss.all, sty.fifa22Cover3)}
            />

            <div
              data-plasmic-name={"rectangle39"}
              data-plasmic-override={overrides.rectangle39}
              className={classNames(projectcss.all, sty.rectangle39)}
            />

            <Ellipse20Icon
              className={classNames(projectcss.all, sty.svg__rjsxL)}
              role={"img"}
            />

            <div
              data-plasmic-name={"subcaption"}
              data-plasmic-override={overrides.subcaption}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.subcaption
              )}
            >
              {"FIFA 2021 with Alex."}
            </div>
            <div
              data-plasmic-name={"rectangle6"}
              data-plasmic-override={overrides.rectangle6}
              className={classNames(projectcss.all, sty.rectangle6)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__moJfQ
              )}
            >
              {"Notifications"}
            </div>
            <div
              data-plasmic-name={"rectangle40"}
              data-plasmic-override={overrides.rectangle40}
              className={classNames(projectcss.all, sty.rectangle40)}
            />

            <Ellipse20Icon
              className={classNames(projectcss.all, sty.svg__itIwz)}
              role={"img"}
            />

            <div
              data-plasmic-name={"subcaption2"}
              data-plasmic-override={overrides.subcaption2}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.subcaption2
              )}
            >
              {"Tom has invited you to play Dota 2."}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__gM5Y
              )}
            >
              {"LAST PLAYED"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__r5Kgy
              )}
            >
              {"2 weeks ago"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__x9HaS
              )}
            >
              {"the sims 4"}
            </div>
            <div
              data-plasmic-name={"dexertoHeader1"}
              data-plasmic-override={overrides.dexertoHeader1}
              className={classNames(projectcss.all, sty.dexertoHeader1)}
            />

            <div
              data-plasmic-name={"sims4HeroBannerDesktop01Ps4Us09Jul191"}
              data-plasmic-override={
                overrides.sims4HeroBannerDesktop01Ps4Us09Jul191
              }
              className={classNames(
                projectcss.all,
                sty.sims4HeroBannerDesktop01Ps4Us09Jul191
              )}
            />

            <div
              data-plasmic-name={"_611551"}
              data-plasmic-override={overrides._611551}
              className={classNames(projectcss.all, sty._611551)}
            />

            <div
              data-plasmic-name={"rectangle42"}
              data-plasmic-override={overrides.rectangle42}
              className={classNames(projectcss.all, sty.rectangle42)}
            />

            <Ellipse20Icon
              className={classNames(projectcss.all, sty.svg__sO7BF)}
              role={"img"}
            />

            <div
              data-plasmic-name={"subcaption3"}
              data-plasmic-override={overrides.subcaption3}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.subcaption3
              )}
            >
              {"Amanda has invited you to play Th.."}
            </div>
            <div
              data-plasmic-name={"_611553"}
              data-plasmic-override={overrides._611553}
              className={classNames(projectcss.all, sty._611553)}
            />

            <div
              data-plasmic-name={"rectangle41"}
              data-plasmic-override={overrides.rectangle41}
              className={classNames(projectcss.all, sty.rectangle41)}
            />

            <Ellipse20Icon
              className={classNames(projectcss.all, sty.svg__i90Mp)}
              role={"img"}
            />

            <div
              data-plasmic-name={"subcaption4"}
              data-plasmic-override={overrides.subcaption4}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.subcaption4
              )}
            >
              {"Alexa has invited you to play Battl.."}
            </div>
            <div
              data-plasmic-name={"_611552"}
              data-plasmic-override={overrides._611552}
              className={classNames(projectcss.all, sty._611552)}
            />

            <div
              data-plasmic-name={
                "computerIconsLikeButtonFriendsIconRemovebgPreview1"
              }
              data-plasmic-override={
                overrides.computerIconsLikeButtonFriendsIconRemovebgPreview1
              }
              className={classNames(
                projectcss.all,
                sty.computerIconsLikeButtonFriendsIconRemovebgPreview1
              )}
            />

            <a
              data-plasmic-name={
                "transparentAvatarIconHumanIconPersonIcon5D678454Ee52E41"
              }
              data-plasmic-override={
                overrides.transparentAvatarIconHumanIconPersonIcon5D678454Ee52E41
              }
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.transparentAvatarIconHumanIconPersonIcon5D678454Ee52E41
              )}
              href={`/friend-list-page`}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "homePage",
    "section",
    "background",
    "rectangle4",
    "image",
    "card",
    "rectangle5",
    "group8",
    "_12983",
    "img",
    "group7",
    "_299Eth",
    "_1DayLeft",
    "image2",
    "sectionSmall",
    "icon",
    "image3",
    "anNftLikeNoOther",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft",
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9",
    "header",
    "logo2",
    "nftlanding2",
    "navigation",
    "h3",
    "h32",
    "rectangle33",
    "rectangle34",
    "fifa22Cover2",
    "battlefield2042CoverArt1",
    "rectangle37",
    "rectangle38",
    "fifa22Cover4",
    "rectangle35",
    "rectangle36",
    "fifa22Cover3",
    "rectangle39",
    "subcaption",
    "rectangle6",
    "rectangle40",
    "subcaption2",
    "dexertoHeader1",
    "sims4HeroBannerDesktop01Ps4Us09Jul191",
    "_611551",
    "rectangle42",
    "subcaption3",
    "_611553",
    "rectangle41",
    "subcaption4",
    "_611552",
    "computerIconsLikeButtonFriendsIconRemovebgPreview1",
    "transparentAvatarIconHumanIconPersonIcon5D678454Ee52E41"
  ],

  homePage: [
    "homePage",
    "section",
    "background",
    "rectangle4",
    "image",
    "card",
    "rectangle5",
    "group8",
    "_12983",
    "img",
    "group7",
    "_299Eth",
    "_1DayLeft",
    "image2",
    "sectionSmall",
    "icon",
    "image3",
    "anNftLikeNoOther",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft",
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9",
    "header",
    "logo2",
    "nftlanding2",
    "navigation",
    "h3",
    "h32",
    "rectangle33",
    "rectangle34",
    "fifa22Cover2",
    "battlefield2042CoverArt1",
    "rectangle37",
    "rectangle38",
    "fifa22Cover4",
    "rectangle35",
    "rectangle36",
    "fifa22Cover3",
    "rectangle39",
    "subcaption",
    "rectangle6",
    "rectangle40",
    "subcaption2",
    "dexertoHeader1",
    "sims4HeroBannerDesktop01Ps4Us09Jul191",
    "_611551",
    "rectangle42",
    "subcaption3",
    "_611553",
    "rectangle41",
    "subcaption4",
    "_611552",
    "computerIconsLikeButtonFriendsIconRemovebgPreview1",
    "transparentAvatarIconHumanIconPersonIcon5D678454Ee52E41"
  ],

  section: [
    "section",
    "background",
    "rectangle4",
    "image",
    "card",
    "rectangle5",
    "group8",
    "_12983",
    "img",
    "group7",
    "_299Eth",
    "_1DayLeft",
    "image2"
  ],

  background: ["background", "rectangle4"],
  rectangle4: ["rectangle4"],
  image: [
    "image",
    "card",
    "rectangle5",
    "group8",
    "_12983",
    "img",
    "group7",
    "_299Eth",
    "_1DayLeft",
    "image2"
  ],

  card: [
    "card",
    "rectangle5",
    "group8",
    "_12983",
    "img",
    "group7",
    "_299Eth",
    "_1DayLeft",
    "image2"
  ],

  rectangle5: ["rectangle5"],
  group8: ["group8", "_12983"],
  _12983: ["_12983"],
  img: ["img"],
  group7: ["group7", "_299Eth", "_1DayLeft", "image2"],
  _299Eth: ["_299Eth"],
  _1DayLeft: ["_1DayLeft"],
  image2: ["image2"],
  sectionSmall: [
    "sectionSmall",
    "icon",
    "image3",
    "anNftLikeNoOther",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft"
  ],

  icon: ["icon", "image3"],
  image3: ["image3"],
  anNftLikeNoOther: ["anNftLikeNoOther"],
  dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft:
    [
      "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft"
    ],

  footer: [
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9"
  ],

  bottom: ["bottom"],
  right: ["right"],
  left: ["left", "logo", "nftlanding"],
  logo: ["logo", "nftlanding"],
  nftlanding: ["nftlanding"],
  divider: ["divider", "rectangle9"],
  rectangle9: ["rectangle9"],
  header: ["header", "logo2", "nftlanding2", "navigation"],
  logo2: ["logo2", "nftlanding2"],
  nftlanding2: ["nftlanding2"],
  navigation: ["navigation"],
  h3: ["h3", "h32"],
  h32: ["h32"],
  rectangle33: ["rectangle33"],
  rectangle34: ["rectangle34"],
  fifa22Cover2: ["fifa22Cover2"],
  battlefield2042CoverArt1: ["battlefield2042CoverArt1"],
  rectangle37: ["rectangle37"],
  rectangle38: ["rectangle38"],
  fifa22Cover4: ["fifa22Cover4"],
  rectangle35: ["rectangle35"],
  rectangle36: ["rectangle36"],
  fifa22Cover3: ["fifa22Cover3"],
  rectangle39: ["rectangle39"],
  subcaption: ["subcaption"],
  rectangle6: ["rectangle6"],
  rectangle40: ["rectangle40"],
  subcaption2: ["subcaption2"],
  dexertoHeader1: ["dexertoHeader1"],
  sims4HeroBannerDesktop01Ps4Us09Jul191: [
    "sims4HeroBannerDesktop01Ps4Us09Jul191"
  ],

  _611551: ["_611551"],
  rectangle42: ["rectangle42"],
  subcaption3: ["subcaption3"],
  _611553: ["_611553"],
  rectangle41: ["rectangle41"],
  subcaption4: ["subcaption4"],
  _611552: ["_611552"],
  computerIconsLikeButtonFriendsIconRemovebgPreview1: [
    "computerIconsLikeButtonFriendsIconRemovebgPreview1"
  ],

  transparentAvatarIconHumanIconPersonIcon5D678454Ee52E41: [
    "transparentAvatarIconHumanIconPersonIcon5D678454Ee52E41"
  ]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomePage__ArgProps,
          internalVariantPropNames: PlasmicHomePage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomePage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomePage";
  } else {
    func.displayName = `PlasmicHomePage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomePage = Object.assign(
  // Top-level PlasmicHomePage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    homePage: makeNodeComponent("homePage"),
    section: makeNodeComponent("section"),
    background: makeNodeComponent("background"),
    rectangle4: makeNodeComponent("rectangle4"),
    image: makeNodeComponent("image"),
    card: makeNodeComponent("card"),
    rectangle5: makeNodeComponent("rectangle5"),
    group8: makeNodeComponent("group8"),
    _12983: makeNodeComponent("_12983"),
    img: makeNodeComponent("img"),
    group7: makeNodeComponent("group7"),
    _299Eth: makeNodeComponent("_299Eth"),
    _1DayLeft: makeNodeComponent("_1DayLeft"),
    image2: makeNodeComponent("image2"),
    sectionSmall: makeNodeComponent("sectionSmall"),
    icon: makeNodeComponent("icon"),
    image3: makeNodeComponent("image3"),
    anNftLikeNoOther: makeNodeComponent("anNftLikeNoOther"),
    dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft:
      makeNodeComponent(
        "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft"
      ),
    footer: makeNodeComponent("footer"),
    bottom: makeNodeComponent("bottom"),
    right: makeNodeComponent("right"),
    left: makeNodeComponent("left"),
    logo: makeNodeComponent("logo"),
    nftlanding: makeNodeComponent("nftlanding"),
    divider: makeNodeComponent("divider"),
    rectangle9: makeNodeComponent("rectangle9"),
    header: makeNodeComponent("header"),
    logo2: makeNodeComponent("logo2"),
    nftlanding2: makeNodeComponent("nftlanding2"),
    navigation: makeNodeComponent("navigation"),
    h3: makeNodeComponent("h3"),
    h32: makeNodeComponent("h32"),
    rectangle33: makeNodeComponent("rectangle33"),
    rectangle34: makeNodeComponent("rectangle34"),
    fifa22Cover2: makeNodeComponent("fifa22Cover2"),
    battlefield2042CoverArt1: makeNodeComponent("battlefield2042CoverArt1"),
    rectangle37: makeNodeComponent("rectangle37"),
    rectangle38: makeNodeComponent("rectangle38"),
    fifa22Cover4: makeNodeComponent("fifa22Cover4"),
    rectangle35: makeNodeComponent("rectangle35"),
    rectangle36: makeNodeComponent("rectangle36"),
    fifa22Cover3: makeNodeComponent("fifa22Cover3"),
    rectangle39: makeNodeComponent("rectangle39"),
    subcaption: makeNodeComponent("subcaption"),
    rectangle6: makeNodeComponent("rectangle6"),
    rectangle40: makeNodeComponent("rectangle40"),
    subcaption2: makeNodeComponent("subcaption2"),
    dexertoHeader1: makeNodeComponent("dexertoHeader1"),
    sims4HeroBannerDesktop01Ps4Us09Jul191: makeNodeComponent(
      "sims4HeroBannerDesktop01Ps4Us09Jul191"
    ),
    _611551: makeNodeComponent("_611551"),
    rectangle42: makeNodeComponent("rectangle42"),
    subcaption3: makeNodeComponent("subcaption3"),
    _611553: makeNodeComponent("_611553"),
    rectangle41: makeNodeComponent("rectangle41"),
    subcaption4: makeNodeComponent("subcaption4"),
    _611552: makeNodeComponent("_611552"),
    computerIconsLikeButtonFriendsIconRemovebgPreview1: makeNodeComponent(
      "computerIconsLikeButtonFriendsIconRemovebgPreview1"
    ),
    transparentAvatarIconHumanIconPersonIcon5D678454Ee52E41: makeNodeComponent(
      "transparentAvatarIconHumanIconPersonIcon5D678454Ee52E41"
    ),
    // Metadata about props expected for PlasmicHomePage
    internalVariantProps: PlasmicHomePage__VariantProps,
    internalArgProps: PlasmicHomePage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomePage;
/* prettier-ignore-end */
