// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ivhpgazgw15hPKwKsPQEWr
// Component: TP55cfiVbF
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_game_schedule.module.css"; // plasmic-import: ivhpgazgw15hPKwKsPQEWr/projectcss
import sty from "./PlasmicCalendarPage1.module.css"; // plasmic-import: TP55cfiVbF/css
import CalendarIcon from "./icons/PlasmicIcon__Calendar"; // plasmic-import: Qd0HtMWJoC/icon
import NavigationIcon from "./icons/PlasmicIcon__Navigation"; // plasmic-import: MTN5rfULbW/icon
import ArrowRightIcon from "./icons/PlasmicIcon__ArrowRight"; // plasmic-import: jm6MdHig87/icon
import EllipseIcon from "./icons/PlasmicIcon__Ellipse"; // plasmic-import: EWVxqM5hq7/icon
import ArrowLeftIcon from "./icons/PlasmicIcon__ArrowLeft"; // plasmic-import: LWD6uGxiaP/icon
import ChevronLeftIcon from "./icons/PlasmicIcon__ChevronLeft"; // plasmic-import: oaINC_mE27/icon
import ArrowRight2Icon from "./icons/PlasmicIcon__ArrowRight2"; // plasmic-import: J51gYEzBJp/icon
import ChevronRightIcon from "./icons/PlasmicIcon__ChevronRight"; // plasmic-import: qRioISSCsU/icon
import ArrowLeft2Icon from "./icons/PlasmicIcon__ArrowLeft2"; // plasmic-import: Gqat7s6WF_/icon
import ArrowLeft3Icon from "./icons/PlasmicIcon__ArrowLeft3"; // plasmic-import: CZHzv3uxaY/icon
import ChevronLeft2Icon from "./icons/PlasmicIcon__ChevronLeft2"; // plasmic-import: 2fk3Ex8lDn/icon
import ArrowRight3Icon from "./icons/PlasmicIcon__ArrowRight3"; // plasmic-import: 30eIxmHayh/icon
import ChevronRight2Icon from "./icons/PlasmicIcon__ChevronRight2"; // plasmic-import: Cb_AezMncm/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: z1kTwBx_qd/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: F4m3gz-3un/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: PrirbzmwPkI/icon
import ellipse23ToW7HpsuG from "./images/ellipse2.svg"; // plasmic-import: 3toW7HpsuG/picture

export const PlasmicCalendarPage1__VariantProps = new Array();

export const PlasmicCalendarPage1__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicCalendarPage1__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"calendarPage1"}
            data-plasmic-override={overrides.calendarPage1}
            className={classNames(projectcss.all, sty.calendarPage1)}
          >
            <div
              data-plasmic-name={"search"}
              data-plasmic-override={overrides.search}
              className={classNames(projectcss.all, sty.search)}
            />

            <div
              data-plasmic-name={"dropdown"}
              data-plasmic-override={overrides.dropdown}
              className={classNames(projectcss.all, sty.dropdown)}
            >
              <div
                data-plasmic-name={"outlineBg"}
                data-plasmic-override={overrides.outlineBg}
                className={classNames(projectcss.all, sty.outlineBg)}
              />

              {false ? (
                <div
                  data-plasmic-name={"background0Dp"}
                  data-plasmic-override={overrides.background0Dp}
                  className={classNames(projectcss.all, sty.background0Dp)}
                >
                  <div
                    data-plasmic-name={"cardBg"}
                    data-plasmic-override={overrides.cardBg}
                    className={classNames(projectcss.all, sty.cardBg)}
                  />
                </div>
              ) : null}
              <div
                data-plasmic-name={"placeholder"}
                data-plasmic-override={overrides.placeholder}
                className={classNames(projectcss.all, sty.placeholder)}
              >
                <div
                  data-plasmic-name={"placeholder2"}
                  data-plasmic-override={overrides.placeholder2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.placeholder2
                  )}
                >
                  {"Add Friends"}
                </div>
              </div>
              <div
                data-plasmic-name={"caption"}
                data-plasmic-override={overrides.caption}
                className={classNames(projectcss.all, sty.caption)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"caption2"}
                    data-plasmic-override={overrides.caption2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.caption2
                    )}
                  >
                    {"Min. Beds"}
                  </div>
                ) : null}
              </div>
            </div>
            <div
              data-plasmic-name={"chevronDown"}
              data-plasmic-override={overrides.chevronDown}
              className={classNames(projectcss.all, sty.chevronDown)}
            />

            <div
              data-plasmic-name={"dropdown2"}
              data-plasmic-override={overrides.dropdown2}
              className={classNames(projectcss.all, sty.dropdown2)}
            >
              <div
                data-plasmic-name={"outlineBg2"}
                data-plasmic-override={overrides.outlineBg2}
                className={classNames(projectcss.all, sty.outlineBg2)}
              />

              {false ? (
                <div
                  data-plasmic-name={"background0Dp2"}
                  data-plasmic-override={overrides.background0Dp2}
                  className={classNames(projectcss.all, sty.background0Dp2)}
                >
                  <div
                    data-plasmic-name={"cardBg2"}
                    data-plasmic-override={overrides.cardBg2}
                    className={classNames(projectcss.all, sty.cardBg2)}
                  />
                </div>
              ) : null}
              <div
                data-plasmic-name={"placeholder3"}
                data-plasmic-override={overrides.placeholder3}
                className={classNames(projectcss.all, sty.placeholder3)}
              >
                <div
                  data-plasmic-name={"placeholder4"}
                  data-plasmic-override={overrides.placeholder4}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.placeholder4
                  )}
                >
                  {"2 May 2022"}
                </div>
              </div>
              <div
                data-plasmic-name={"caption3"}
                data-plasmic-override={overrides.caption3}
                className={classNames(projectcss.all, sty.caption3)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"caption4"}
                    data-plasmic-override={overrides.caption4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.caption4
                    )}
                  >
                    {"Min. Beds"}
                  </div>
                ) : null}
              </div>
              <CalendarIcon
                className={classNames(projectcss.all, sty.svg__idlc4)}
                role={"img"}
              />
            </div>
            <div
              data-plasmic-name={"_28304011"}
              data-plasmic-override={overrides._28304011}
              className={classNames(projectcss.all, sty._28304011)}
            />

            <div
              data-plasmic-name={"outlineBg3"}
              data-plasmic-override={overrides.outlineBg3}
              className={classNames(projectcss.all, sty.outlineBg3)}
            />

            <div
              data-plasmic-name={"outlineBg4"}
              data-plasmic-override={overrides.outlineBg4}
              className={classNames(projectcss.all, sty.outlineBg4)}
            />

            <div
              data-plasmic-name={"placeholder5"}
              data-plasmic-override={overrides.placeholder5}
              className={classNames(projectcss.all, sty.placeholder5)}
            >
              <div
                data-plasmic-name={"placeholder6"}
                data-plasmic-override={overrides.placeholder6}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.placeholder6
                )}
              >
                {"Game — Apex Legends"}
              </div>
            </div>
            <div
              data-plasmic-name={"placeholder7"}
              data-plasmic-override={overrides.placeholder7}
              className={classNames(projectcss.all, sty.placeholder7)}
            >
              <div
                data-plasmic-name={"placeholder8"}
                data-plasmic-override={overrides.placeholder8}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.placeholder8
                )}
              >
                {"Filters"}
              </div>
            </div>
            <NavigationIcon
              className={classNames(projectcss.all, sty.svg__hkHcx)}
              role={"img"}
            />

            <div
              data-plasmic-name={"cardBg3"}
              data-plasmic-override={overrides.cardBg3}
              className={classNames(projectcss.all, sty.cardBg3)}
            />

            <ArrowRightIcon
              className={classNames(projectcss.all, sty.svg__xKzXx)}
              role={"img"}
            />

            <div
              data-plasmic-name={"calendar"}
              data-plasmic-override={overrides.calendar}
              className={classNames(projectcss.all, sty.calendar)}
            >
              {false ? (
                <div
                  data-plasmic-name={"background0Dp3"}
                  data-plasmic-override={overrides.background0Dp3}
                  className={classNames(projectcss.all, sty.background0Dp3)}
                >
                  <div
                    data-plasmic-name={"cardBg4"}
                    data-plasmic-override={overrides.cardBg4}
                    className={classNames(projectcss.all, sty.cardBg4)}
                  />
                </div>
              ) : null}
              {false ? (
                <div
                  data-plasmic-name={"selector"}
                  data-plasmic-override={overrides.selector}
                  className={classNames(projectcss.all, sty.selector)}
                >
                  <div
                    data-plasmic-name={"selector2"}
                    data-plasmic-override={overrides.selector2}
                    className={classNames(projectcss.all, sty.selector2)}
                  >
                    <div
                      data-plasmic-name={"rectangle2"}
                      data-plasmic-override={overrides.rectangle2}
                      className={classNames(projectcss.all, sty.rectangle2)}
                    />
                  </div>
                  <div
                    data-plasmic-name={"selector3"}
                    data-plasmic-override={overrides.selector3}
                    className={classNames(projectcss.all, sty.selector3)}
                  >
                    <div
                      data-plasmic-name={"rectangle3"}
                      data-plasmic-override={overrides.rectangle3}
                      className={classNames(projectcss.all, sty.rectangle3)}
                    />
                  </div>
                  <div
                    data-plasmic-name={"selector4"}
                    data-plasmic-override={overrides.selector4}
                    className={classNames(projectcss.all, sty.selector4)}
                  >
                    <div
                      data-plasmic-name={"rectangle4"}
                      data-plasmic-override={overrides.rectangle4}
                      className={classNames(projectcss.all, sty.rectangle4)}
                    />
                  </div>
                  <div
                    data-plasmic-name={"selector5"}
                    data-plasmic-override={overrides.selector5}
                    className={classNames(projectcss.all, sty.selector5)}
                  >
                    <div
                      data-plasmic-name={"rectangle5"}
                      data-plasmic-override={overrides.rectangle5}
                      className={classNames(projectcss.all, sty.rectangle5)}
                    />
                  </div>
                </div>
              ) : null}
            </div>
            <div
              data-plasmic-name={"calendar2"}
              data-plasmic-override={overrides.calendar2}
              className={classNames(projectcss.all, sty.calendar2)}
            >
              <div
                data-plasmic-name={"date"}
                data-plasmic-override={overrides.date}
                className={classNames(projectcss.all, sty.date)}
              >
                <div
                  data-plasmic-name={"_1Second"}
                  data-plasmic-override={overrides._1Second}
                  className={classNames(projectcss.all, sty._1Second)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__df4Sy)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number"}
                    data-plasmic-override={overrides.number}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number
                    )}
                  >
                    {"1"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_31"}
                  data-plasmic-override={overrides._31}
                  className={classNames(projectcss.all, sty._31)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__k8FHx)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number2"}
                    data-plasmic-override={overrides.number2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number2
                    )}
                  >
                    {"31"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_30Second"}
                  data-plasmic-override={overrides._30Second}
                  className={classNames(projectcss.all, sty._30Second)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__kqR8K)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number3"}
                    data-plasmic-override={overrides.number3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number3
                    )}
                  >
                    {"30"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_29Second"}
                  data-plasmic-override={overrides._29Second}
                  className={classNames(projectcss.all, sty._29Second)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg___9Xhl4)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number4"}
                    data-plasmic-override={overrides.number4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number4
                    )}
                  >
                    {"29"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_28Second"}
                  data-plasmic-override={overrides._28Second}
                  className={classNames(projectcss.all, sty._28Second)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__u9Ia1)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number5"}
                    data-plasmic-override={overrides.number5}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number5
                    )}
                  >
                    {"28"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_27"}
                  data-plasmic-override={overrides._27}
                  className={classNames(projectcss.all, sty._27)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__ve5Yf)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number6"}
                    data-plasmic-override={overrides.number6}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number6
                    )}
                  >
                    {"27"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_26"}
                  data-plasmic-override={overrides._26}
                  className={classNames(projectcss.all, sty._26)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg___0Kwf)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number7"}
                    data-plasmic-override={overrides.number7}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number7
                    )}
                  >
                    {"26"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_25"}
                  data-plasmic-override={overrides._25}
                  className={classNames(projectcss.all, sty._25)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__yshLw)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number8"}
                    data-plasmic-override={overrides.number8}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number8
                    )}
                  >
                    {"25"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_24"}
                  data-plasmic-override={overrides._24}
                  className={classNames(projectcss.all, sty._24)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__do5B)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number9"}
                    data-plasmic-override={overrides.number9}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number9
                    )}
                  >
                    {"24"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_23"}
                  data-plasmic-override={overrides._23}
                  className={classNames(projectcss.all, sty._23)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__xbKwk)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number10"}
                    data-plasmic-override={overrides.number10}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number10
                    )}
                  >
                    {"23"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_22"}
                  data-plasmic-override={overrides._22}
                  className={classNames(projectcss.all, sty._22)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg___7BdG8)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number11"}
                    data-plasmic-override={overrides.number11}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number11
                    )}
                  >
                    {"22"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_20"}
                  data-plasmic-override={overrides._20}
                  className={classNames(projectcss.all, sty._20)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__lb0Po)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number12"}
                    data-plasmic-override={overrides.number12}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number12
                    )}
                  >
                    {"20"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_19"}
                  data-plasmic-override={overrides._19}
                  className={classNames(projectcss.all, sty._19)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__sczDk)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number13"}
                    data-plasmic-override={overrides.number13}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number13
                    )}
                  >
                    {"19"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_18"}
                  data-plasmic-override={overrides._18}
                  className={classNames(projectcss.all, sty._18)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__uuqHu)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number14"}
                    data-plasmic-override={overrides.number14}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number14
                    )}
                  >
                    {"18"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_17"}
                  data-plasmic-override={overrides._17}
                  className={classNames(projectcss.all, sty._17)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__y0YM8)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number15"}
                    data-plasmic-override={overrides.number15}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number15
                    )}
                  >
                    {"17"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_16"}
                  data-plasmic-override={overrides._16}
                  className={classNames(projectcss.all, sty._16)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__dyge)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number16"}
                    data-plasmic-override={overrides.number16}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number16
                    )}
                  >
                    {"16"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_15"}
                  data-plasmic-override={overrides._15}
                  className={classNames(projectcss.all, sty._15)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__wewvS)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number17"}
                    data-plasmic-override={overrides.number17}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number17
                    )}
                  >
                    {"15"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_14"}
                  data-plasmic-override={overrides._14}
                  className={classNames(projectcss.all, sty._14)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__pKoGh)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number18"}
                    data-plasmic-override={overrides.number18}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number18
                    )}
                  >
                    {"14"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_13"}
                  data-plasmic-override={overrides._13}
                  className={classNames(projectcss.all, sty._13)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__kVsqJ)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number19"}
                    data-plasmic-override={overrides.number19}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number19
                    )}
                  >
                    {"13"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_12"}
                  data-plasmic-override={overrides._12}
                  className={classNames(projectcss.all, sty._12)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__iFtpV)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number20"}
                    data-plasmic-override={overrides.number20}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number20
                    )}
                  >
                    {"12"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_11"}
                  data-plasmic-override={overrides._11}
                  className={classNames(projectcss.all, sty._11)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__gaJv6)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number21"}
                    data-plasmic-override={overrides.number21}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number21
                    )}
                  >
                    {"11"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_10"}
                  data-plasmic-override={overrides._10}
                  className={classNames(projectcss.all, sty._10)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__q9Ua8)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number22"}
                    data-plasmic-override={overrides.number22}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number22
                    )}
                  >
                    {"10"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_9"}
                  data-plasmic-override={overrides._9}
                  className={classNames(projectcss.all, sty._9)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__qrjFf)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number23"}
                    data-plasmic-override={overrides.number23}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number23
                    )}
                  >
                    {"9"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_8"}
                  data-plasmic-override={overrides._8}
                  className={classNames(projectcss.all, sty._8)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__wpQzA)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number24"}
                    data-plasmic-override={overrides.number24}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number24
                    )}
                  >
                    {"8"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_7"}
                  data-plasmic-override={overrides._7}
                  className={classNames(projectcss.all, sty._7)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__nt1JA)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number25"}
                    data-plasmic-override={overrides.number25}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number25
                    )}
                  >
                    {"7"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_6"}
                  data-plasmic-override={overrides._6}
                  className={classNames(projectcss.all, sty._6)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__lxya1)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number26"}
                    data-plasmic-override={overrides.number26}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number26
                    )}
                  >
                    {"6"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_5"}
                  data-plasmic-override={overrides._5}
                  className={classNames(projectcss.all, sty._5)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg___8KVoC)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number27"}
                    data-plasmic-override={overrides.number27}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number27
                    )}
                  >
                    {"5"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_4"}
                  data-plasmic-override={overrides._4}
                  className={classNames(projectcss.all, sty._4)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__upEQd)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number28"}
                    data-plasmic-override={overrides.number28}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number28
                    )}
                  >
                    {"4"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_3"}
                  data-plasmic-override={overrides._3}
                  className={classNames(projectcss.all, sty._3)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__mClN6)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number29"}
                    data-plasmic-override={overrides.number29}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number29
                    )}
                  >
                    {"3"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_2"}
                  data-plasmic-override={overrides._2}
                  className={classNames(projectcss.all, sty._2)}
                >
                  <p.PlasmicImg
                    data-plasmic-name={"img"}
                    data-plasmic-override={overrides.img}
                    alt={""}
                    className={classNames(sty.img)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: ellipse23ToW7HpsuG,
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />

                  <div
                    data-plasmic-name={"number30"}
                    data-plasmic-override={overrides.number30}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number30
                    )}
                  >
                    {"2"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"numeral"}
                  data-plasmic-override={overrides.numeral}
                  className={classNames(projectcss.all, sty.numeral)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg___6JdY0)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number31"}
                    data-plasmic-override={overrides.number31}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number31
                    )}
                  >
                    {"1"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_30First"}
                  data-plasmic-override={overrides._30First}
                  className={classNames(projectcss.all, sty._30First)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__rPme3)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number32"}
                    data-plasmic-override={overrides.number32}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number32
                    )}
                  >
                    {"30"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_29First"}
                  data-plasmic-override={overrides._29First}
                  className={classNames(projectcss.all, sty._29First)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg__jbnci)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number33"}
                    data-plasmic-override={overrides.number33}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number33
                    )}
                  >
                    {"29"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"_28First"}
                  data-plasmic-override={overrides._28First}
                  className={classNames(projectcss.all, sty._28First)}
                >
                  {false ? (
                    <EllipseIcon
                      className={classNames(projectcss.all, sty.svg___1KdG)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"number34"}
                    data-plasmic-override={overrides.number34}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.number34
                    )}
                  >
                    {"28"}
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"_32"}
                data-plasmic-override={overrides._32}
                className={classNames(projectcss.all, sty._32)}
              >
                {false ? (
                  <EllipseIcon
                    className={classNames(projectcss.all, sty.svg__j2RDf)}
                    role={"img"}
                  />
                ) : null}
                <div
                  data-plasmic-name={"number35"}
                  data-plasmic-override={overrides.number35}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.number35
                  )}
                >
                  {"21"}
                </div>
              </div>
              <div
                data-plasmic-name={"daysOfTheWeek"}
                data-plasmic-override={overrides.daysOfTheWeek}
                className={classNames(projectcss.all, sty.daysOfTheWeek)}
              >
                <div
                  data-plasmic-name={"sat"}
                  data-plasmic-override={overrides.sat}
                  className={classNames(projectcss.all, sty.sat)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tM6Cg
                    )}
                  >
                    {"SAT"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"fri"}
                  data-plasmic-override={overrides.fri}
                  className={classNames(projectcss.all, sty.fri)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6W2
                    )}
                  >
                    {"FRI"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"thu"}
                  data-plasmic-override={overrides.thu}
                  className={classNames(projectcss.all, sty.thu)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8NGfW
                    )}
                  >
                    {"THU"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"wed"}
                  data-plasmic-override={overrides.wed}
                  className={classNames(projectcss.all, sty.wed)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lu6CR
                    )}
                  >
                    {"WED"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"tue"}
                  data-plasmic-override={overrides.tue}
                  className={classNames(projectcss.all, sty.tue)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0ZLfN
                    )}
                  >
                    {"TUE"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"mon"}
                  data-plasmic-override={overrides.mon}
                  className={classNames(projectcss.all, sty.mon)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__y5Le9
                    )}
                  >
                    {"MON"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"sun"}
                  data-plasmic-override={overrides.sun}
                  className={classNames(projectcss.all, sty.sun)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nnP2O
                    )}
                  >
                    {"SUN"}
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"buttonOutlineXs"}
                data-plasmic-override={overrides.buttonOutlineXs}
                className={classNames(projectcss.all, sty.buttonOutlineXs)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"buttonBg"}
                    data-plasmic-override={overrides.buttonBg}
                    className={classNames(projectcss.all, sty.buttonBg)}
                  />
                ) : null}
                <div
                  data-plasmic-name={"caption5"}
                  data-plasmic-override={overrides.caption5}
                  className={classNames(projectcss.all, sty.caption5)}
                >
                  <div
                    data-plasmic-name={"caption6"}
                    data-plasmic-override={overrides.caption6}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.caption6
                    )}
                  >
                    {"May 2022"}
                  </div>
                </div>
                {false ? (
                  <div
                    data-plasmic-name={"left"}
                    data-plasmic-override={overrides.left}
                    className={classNames(projectcss.all, sty.left)}
                  >
                    {false ? (
                      <ArrowLeftIcon
                        className={classNames(projectcss.all, sty.svg___0K5F1)}
                        role={"img"}
                      />
                    ) : null}
                    <ChevronLeftIcon
                      className={classNames(projectcss.all, sty.svg___6MZ4)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                {false ? (
                  <div
                    data-plasmic-name={"right"}
                    data-plasmic-override={overrides.right}
                    className={classNames(projectcss.all, sty.right)}
                  >
                    {false ? (
                      <ArrowRight2Icon
                        className={classNames(projectcss.all, sty.svg__dX5Y6)}
                        role={"img"}
                      />
                    ) : null}
                    {false ? (
                      <ChevronRightIcon
                        className={classNames(projectcss.all, sty.svg__s5IiJ)}
                        role={"img"}
                      />
                    ) : null}
                  </div>
                ) : null}
              </div>
            </div>
            <ArrowLeft2Icon
              className={classNames(projectcss.all, sty.svg__ivczp)}
              role={"img"}
            />

            <div
              data-plasmic-name={"segmented"}
              data-plasmic-override={overrides.segmented}
              className={classNames(projectcss.all, sty.segmented)}
            >
              <div
                data-plasmic-name={"background0Dp4"}
                data-plasmic-override={overrides.background0Dp4}
                className={classNames(projectcss.all, sty.background0Dp4)}
              >
                <div
                  data-plasmic-name={"cardBg5"}
                  data-plasmic-override={overrides.cardBg5}
                  className={classNames(projectcss.all, sty.cardBg5)}
                />
              </div>
              <div
                data-plasmic-name={"buttonLightXs"}
                data-plasmic-override={overrides.buttonLightXs}
                className={classNames(projectcss.all, sty.buttonLightXs)}
              >
                <div
                  data-plasmic-name={"buttonBg2"}
                  data-plasmic-override={overrides.buttonBg2}
                  className={classNames(projectcss.all, sty.buttonBg2)}
                />

                <div
                  data-plasmic-name={"caption7"}
                  data-plasmic-override={overrides.caption7}
                  className={classNames(projectcss.all, sty.caption7)}
                >
                  <div
                    data-plasmic-name={"caption8"}
                    data-plasmic-override={overrides.caption8}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.caption8
                    )}
                  >
                    {"Default"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"left2"}
                  data-plasmic-override={overrides.left2}
                  className={classNames(projectcss.all, sty.left2)}
                >
                  {false ? (
                    <ArrowLeft3Icon
                      className={classNames(projectcss.all, sty.svg__f72Q)}
                      role={"img"}
                    />
                  ) : null}
                  {false ? (
                    <ChevronLeft2Icon
                      className={classNames(projectcss.all, sty.svg__rUaMy)}
                      role={"img"}
                    />
                  ) : null}
                </div>
                <div
                  data-plasmic-name={"right2"}
                  data-plasmic-override={overrides.right2}
                  className={classNames(projectcss.all, sty.right2)}
                >
                  {false ? (
                    <ArrowRight3Icon
                      className={classNames(projectcss.all, sty.svg__buZ0G)}
                      role={"img"}
                    />
                  ) : null}
                  {false ? (
                    <ChevronRight2Icon
                      className={classNames(projectcss.all, sty.svg__nP3K5)}
                      role={"img"}
                    />
                  ) : null}
                </div>
              </div>
              <div
                data-plasmic-name={"buttonOutlineXs2"}
                data-plasmic-override={overrides.buttonOutlineXs2}
                className={classNames(projectcss.all, sty.buttonOutlineXs2)}
              >
                <div
                  data-plasmic-name={"buttonBg3"}
                  data-plasmic-override={overrides.buttonBg3}
                  className={classNames(projectcss.all, sty.buttonBg3)}
                />

                <div
                  data-plasmic-name={"caption9"}
                  data-plasmic-override={overrides.caption9}
                  className={classNames(projectcss.all, sty.caption9)}
                >
                  <div
                    data-plasmic-name={"caption10"}
                    data-plasmic-override={overrides.caption10}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.caption10
                    )}
                  >
                    {"Selected"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"left3"}
                  data-plasmic-override={overrides.left3}
                  className={classNames(projectcss.all, sty.left3)}
                >
                  {false ? (
                    <ArrowLeftIcon
                      className={classNames(projectcss.all, sty.svg__kWo80)}
                      role={"img"}
                    />
                  ) : null}
                  {false ? (
                    <ChevronLeftIcon
                      className={classNames(projectcss.all, sty.svg__lmats)}
                      role={"img"}
                    />
                  ) : null}
                </div>
                <div
                  data-plasmic-name={"right3"}
                  data-plasmic-override={overrides.right3}
                  className={classNames(projectcss.all, sty.right3)}
                >
                  {false ? (
                    <ArrowRight2Icon
                      className={classNames(projectcss.all, sty.svg___25ZL7)}
                      role={"img"}
                    />
                  ) : null}
                  {false ? (
                    <ChevronRightIcon
                      className={classNames(projectcss.all, sty.svg__pCSu)}
                      role={"img"}
                    />
                  ) : null}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"h3"}
              data-plasmic-override={overrides.h3}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.h3
              )}
            >
              {"Your Calendar"}
            </div>
            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__xeeOc)}
              role={"img"}
            />

            <VectorIcon
              className={classNames(projectcss.all, sty.svg__ezQ71)}
              role={"img"}
            />

            <div
              data-plasmic-name={"subcaption"}
              data-plasmic-override={overrides.subcaption}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.subcaption
              )}
            >
              {"Choose a day to schedule your game session."}
            </div>
            <div
              data-plasmic-name={"h6"}
              data-plasmic-override={overrides.h6}
              className={classNames(projectcss.all, sty.h6)}
            >
              <div
                data-plasmic-name={"h62"}
                data-plasmic-override={overrides.h62}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.h62
                )}
              >
                {"Day Selector"}
              </div>
            </div>
            <div
              data-plasmic-name={"loginBtn"}
              data-plasmic-override={overrides.loginBtn}
              className={classNames(projectcss.all, sty.loginBtn)}
            >
              <a
                data-plasmic-name={"rectangle"}
                data-plasmic-override={overrides.rectangle}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.rectangle
                )}
                href={`/calendar-page-2`}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__emNy7
                )}
              >
                {"SELECT"}
              </div>
            </div>
            <Vector3Icon
              className={classNames(projectcss.all, sty.svg__ygo3W)}
              role={"img"}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "calendarPage1",
    "search",
    "dropdown",
    "outlineBg",
    "background0Dp",
    "cardBg",
    "placeholder",
    "placeholder2",
    "caption",
    "caption2",
    "chevronDown",
    "dropdown2",
    "outlineBg2",
    "background0Dp2",
    "cardBg2",
    "placeholder3",
    "placeholder4",
    "caption3",
    "caption4",
    "_28304011",
    "outlineBg3",
    "outlineBg4",
    "placeholder5",
    "placeholder6",
    "placeholder7",
    "placeholder8",
    "cardBg3",
    "calendar",
    "background0Dp3",
    "cardBg4",
    "selector",
    "selector2",
    "rectangle2",
    "selector3",
    "rectangle3",
    "selector4",
    "rectangle4",
    "selector5",
    "rectangle5",
    "calendar2",
    "date",
    "_1Second",
    "number",
    "_31",
    "number2",
    "_30Second",
    "number3",
    "_29Second",
    "number4",
    "_28Second",
    "number5",
    "_27",
    "number6",
    "_26",
    "number7",
    "_25",
    "number8",
    "_24",
    "number9",
    "_23",
    "number10",
    "_22",
    "number11",
    "_20",
    "number12",
    "_19",
    "number13",
    "_18",
    "number14",
    "_17",
    "number15",
    "_16",
    "number16",
    "_15",
    "number17",
    "_14",
    "number18",
    "_13",
    "number19",
    "_12",
    "number20",
    "_11",
    "number21",
    "_10",
    "number22",
    "_9",
    "number23",
    "_8",
    "number24",
    "_7",
    "number25",
    "_6",
    "number26",
    "_5",
    "number27",
    "_4",
    "number28",
    "_3",
    "number29",
    "_2",
    "img",
    "number30",
    "numeral",
    "number31",
    "_30First",
    "number32",
    "_29First",
    "number33",
    "_28First",
    "number34",
    "_32",
    "number35",
    "daysOfTheWeek",
    "sat",
    "fri",
    "thu",
    "wed",
    "tue",
    "mon",
    "sun",
    "buttonOutlineXs",
    "buttonBg",
    "caption5",
    "caption6",
    "left",
    "right",
    "segmented",
    "background0Dp4",
    "cardBg5",
    "buttonLightXs",
    "buttonBg2",
    "caption7",
    "caption8",
    "left2",
    "right2",
    "buttonOutlineXs2",
    "buttonBg3",
    "caption9",
    "caption10",
    "left3",
    "right3",
    "h3",
    "subcaption",
    "h6",
    "h62",
    "loginBtn",
    "rectangle"
  ],

  calendarPage1: [
    "calendarPage1",
    "search",
    "dropdown",
    "outlineBg",
    "background0Dp",
    "cardBg",
    "placeholder",
    "placeholder2",
    "caption",
    "caption2",
    "chevronDown",
    "dropdown2",
    "outlineBg2",
    "background0Dp2",
    "cardBg2",
    "placeholder3",
    "placeholder4",
    "caption3",
    "caption4",
    "_28304011",
    "outlineBg3",
    "outlineBg4",
    "placeholder5",
    "placeholder6",
    "placeholder7",
    "placeholder8",
    "cardBg3",
    "calendar",
    "background0Dp3",
    "cardBg4",
    "selector",
    "selector2",
    "rectangle2",
    "selector3",
    "rectangle3",
    "selector4",
    "rectangle4",
    "selector5",
    "rectangle5",
    "calendar2",
    "date",
    "_1Second",
    "number",
    "_31",
    "number2",
    "_30Second",
    "number3",
    "_29Second",
    "number4",
    "_28Second",
    "number5",
    "_27",
    "number6",
    "_26",
    "number7",
    "_25",
    "number8",
    "_24",
    "number9",
    "_23",
    "number10",
    "_22",
    "number11",
    "_20",
    "number12",
    "_19",
    "number13",
    "_18",
    "number14",
    "_17",
    "number15",
    "_16",
    "number16",
    "_15",
    "number17",
    "_14",
    "number18",
    "_13",
    "number19",
    "_12",
    "number20",
    "_11",
    "number21",
    "_10",
    "number22",
    "_9",
    "number23",
    "_8",
    "number24",
    "_7",
    "number25",
    "_6",
    "number26",
    "_5",
    "number27",
    "_4",
    "number28",
    "_3",
    "number29",
    "_2",
    "img",
    "number30",
    "numeral",
    "number31",
    "_30First",
    "number32",
    "_29First",
    "number33",
    "_28First",
    "number34",
    "_32",
    "number35",
    "daysOfTheWeek",
    "sat",
    "fri",
    "thu",
    "wed",
    "tue",
    "mon",
    "sun",
    "buttonOutlineXs",
    "buttonBg",
    "caption5",
    "caption6",
    "left",
    "right",
    "segmented",
    "background0Dp4",
    "cardBg5",
    "buttonLightXs",
    "buttonBg2",
    "caption7",
    "caption8",
    "left2",
    "right2",
    "buttonOutlineXs2",
    "buttonBg3",
    "caption9",
    "caption10",
    "left3",
    "right3",
    "h3",
    "subcaption",
    "h6",
    "h62",
    "loginBtn",
    "rectangle"
  ],

  search: ["search"],
  dropdown: [
    "dropdown",
    "outlineBg",
    "background0Dp",
    "cardBg",
    "placeholder",
    "placeholder2",
    "caption",
    "caption2"
  ],

  outlineBg: ["outlineBg"],
  background0Dp: ["background0Dp", "cardBg"],
  cardBg: ["cardBg"],
  placeholder: ["placeholder", "placeholder2"],
  placeholder2: ["placeholder2"],
  caption: ["caption", "caption2"],
  caption2: ["caption2"],
  chevronDown: ["chevronDown"],
  dropdown2: [
    "dropdown2",
    "outlineBg2",
    "background0Dp2",
    "cardBg2",
    "placeholder3",
    "placeholder4",
    "caption3",
    "caption4"
  ],

  outlineBg2: ["outlineBg2"],
  background0Dp2: ["background0Dp2", "cardBg2"],
  cardBg2: ["cardBg2"],
  placeholder3: ["placeholder3", "placeholder4"],
  placeholder4: ["placeholder4"],
  caption3: ["caption3", "caption4"],
  caption4: ["caption4"],
  _28304011: ["_28304011"],
  outlineBg3: ["outlineBg3"],
  outlineBg4: ["outlineBg4"],
  placeholder5: ["placeholder5", "placeholder6"],
  placeholder6: ["placeholder6"],
  placeholder7: ["placeholder7", "placeholder8"],
  placeholder8: ["placeholder8"],
  cardBg3: ["cardBg3"],
  calendar: [
    "calendar",
    "background0Dp3",
    "cardBg4",
    "selector",
    "selector2",
    "rectangle2",
    "selector3",
    "rectangle3",
    "selector4",
    "rectangle4",
    "selector5",
    "rectangle5"
  ],

  background0Dp3: ["background0Dp3", "cardBg4"],
  cardBg4: ["cardBg4"],
  selector: [
    "selector",
    "selector2",
    "rectangle2",
    "selector3",
    "rectangle3",
    "selector4",
    "rectangle4",
    "selector5",
    "rectangle5"
  ],

  selector2: ["selector2", "rectangle2"],
  rectangle2: ["rectangle2"],
  selector3: ["selector3", "rectangle3"],
  rectangle3: ["rectangle3"],
  selector4: ["selector4", "rectangle4"],
  rectangle4: ["rectangle4"],
  selector5: ["selector5", "rectangle5"],
  rectangle5: ["rectangle5"],
  calendar2: [
    "calendar2",
    "date",
    "_1Second",
    "number",
    "_31",
    "number2",
    "_30Second",
    "number3",
    "_29Second",
    "number4",
    "_28Second",
    "number5",
    "_27",
    "number6",
    "_26",
    "number7",
    "_25",
    "number8",
    "_24",
    "number9",
    "_23",
    "number10",
    "_22",
    "number11",
    "_20",
    "number12",
    "_19",
    "number13",
    "_18",
    "number14",
    "_17",
    "number15",
    "_16",
    "number16",
    "_15",
    "number17",
    "_14",
    "number18",
    "_13",
    "number19",
    "_12",
    "number20",
    "_11",
    "number21",
    "_10",
    "number22",
    "_9",
    "number23",
    "_8",
    "number24",
    "_7",
    "number25",
    "_6",
    "number26",
    "_5",
    "number27",
    "_4",
    "number28",
    "_3",
    "number29",
    "_2",
    "img",
    "number30",
    "numeral",
    "number31",
    "_30First",
    "number32",
    "_29First",
    "number33",
    "_28First",
    "number34",
    "_32",
    "number35",
    "daysOfTheWeek",
    "sat",
    "fri",
    "thu",
    "wed",
    "tue",
    "mon",
    "sun",
    "buttonOutlineXs",
    "buttonBg",
    "caption5",
    "caption6",
    "left",
    "right"
  ],

  date: [
    "date",
    "_1Second",
    "number",
    "_31",
    "number2",
    "_30Second",
    "number3",
    "_29Second",
    "number4",
    "_28Second",
    "number5",
    "_27",
    "number6",
    "_26",
    "number7",
    "_25",
    "number8",
    "_24",
    "number9",
    "_23",
    "number10",
    "_22",
    "number11",
    "_20",
    "number12",
    "_19",
    "number13",
    "_18",
    "number14",
    "_17",
    "number15",
    "_16",
    "number16",
    "_15",
    "number17",
    "_14",
    "number18",
    "_13",
    "number19",
    "_12",
    "number20",
    "_11",
    "number21",
    "_10",
    "number22",
    "_9",
    "number23",
    "_8",
    "number24",
    "_7",
    "number25",
    "_6",
    "number26",
    "_5",
    "number27",
    "_4",
    "number28",
    "_3",
    "number29",
    "_2",
    "img",
    "number30",
    "numeral",
    "number31",
    "_30First",
    "number32",
    "_29First",
    "number33",
    "_28First",
    "number34"
  ],

  _1Second: ["_1Second", "number"],
  number: ["number"],
  _31: ["_31", "number2"],
  number2: ["number2"],
  _30Second: ["_30Second", "number3"],
  number3: ["number3"],
  _29Second: ["_29Second", "number4"],
  number4: ["number4"],
  _28Second: ["_28Second", "number5"],
  number5: ["number5"],
  _27: ["_27", "number6"],
  number6: ["number6"],
  _26: ["_26", "number7"],
  number7: ["number7"],
  _25: ["_25", "number8"],
  number8: ["number8"],
  _24: ["_24", "number9"],
  number9: ["number9"],
  _23: ["_23", "number10"],
  number10: ["number10"],
  _22: ["_22", "number11"],
  number11: ["number11"],
  _20: ["_20", "number12"],
  number12: ["number12"],
  _19: ["_19", "number13"],
  number13: ["number13"],
  _18: ["_18", "number14"],
  number14: ["number14"],
  _17: ["_17", "number15"],
  number15: ["number15"],
  _16: ["_16", "number16"],
  number16: ["number16"],
  _15: ["_15", "number17"],
  number17: ["number17"],
  _14: ["_14", "number18"],
  number18: ["number18"],
  _13: ["_13", "number19"],
  number19: ["number19"],
  _12: ["_12", "number20"],
  number20: ["number20"],
  _11: ["_11", "number21"],
  number21: ["number21"],
  _10: ["_10", "number22"],
  number22: ["number22"],
  _9: ["_9", "number23"],
  number23: ["number23"],
  _8: ["_8", "number24"],
  number24: ["number24"],
  _7: ["_7", "number25"],
  number25: ["number25"],
  _6: ["_6", "number26"],
  number26: ["number26"],
  _5: ["_5", "number27"],
  number27: ["number27"],
  _4: ["_4", "number28"],
  number28: ["number28"],
  _3: ["_3", "number29"],
  number29: ["number29"],
  _2: ["_2", "img", "number30"],
  img: ["img"],
  number30: ["number30"],
  numeral: ["numeral", "number31"],
  number31: ["number31"],
  _30First: ["_30First", "number32"],
  number32: ["number32"],
  _29First: ["_29First", "number33"],
  number33: ["number33"],
  _28First: ["_28First", "number34"],
  number34: ["number34"],
  _32: ["_32", "number35"],
  number35: ["number35"],
  daysOfTheWeek: [
    "daysOfTheWeek",
    "sat",
    "fri",
    "thu",
    "wed",
    "tue",
    "mon",
    "sun"
  ],

  sat: ["sat"],
  fri: ["fri"],
  thu: ["thu"],
  wed: ["wed"],
  tue: ["tue"],
  mon: ["mon"],
  sun: ["sun"],
  buttonOutlineXs: [
    "buttonOutlineXs",
    "buttonBg",
    "caption5",
    "caption6",
    "left",
    "right"
  ],

  buttonBg: ["buttonBg"],
  caption5: ["caption5", "caption6"],
  caption6: ["caption6"],
  left: ["left"],
  right: ["right"],
  segmented: [
    "segmented",
    "background0Dp4",
    "cardBg5",
    "buttonLightXs",
    "buttonBg2",
    "caption7",
    "caption8",
    "left2",
    "right2",
    "buttonOutlineXs2",
    "buttonBg3",
    "caption9",
    "caption10",
    "left3",
    "right3"
  ],

  background0Dp4: ["background0Dp4", "cardBg5"],
  cardBg5: ["cardBg5"],
  buttonLightXs: [
    "buttonLightXs",
    "buttonBg2",
    "caption7",
    "caption8",
    "left2",
    "right2"
  ],

  buttonBg2: ["buttonBg2"],
  caption7: ["caption7", "caption8"],
  caption8: ["caption8"],
  left2: ["left2"],
  right2: ["right2"],
  buttonOutlineXs2: [
    "buttonOutlineXs2",
    "buttonBg3",
    "caption9",
    "caption10",
    "left3",
    "right3"
  ],

  buttonBg3: ["buttonBg3"],
  caption9: ["caption9", "caption10"],
  caption10: ["caption10"],
  left3: ["left3"],
  right3: ["right3"],
  h3: ["h3"],
  subcaption: ["subcaption"],
  h6: ["h6", "h62"],
  h62: ["h62"],
  loginBtn: ["loginBtn", "rectangle"],
  rectangle: ["rectangle"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCalendarPage1__ArgProps,
          internalVariantPropNames: PlasmicCalendarPage1__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCalendarPage1__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCalendarPage1";
  } else {
    func.displayName = `PlasmicCalendarPage1.${nodeName}`;
  }
  return func;
}

export const PlasmicCalendarPage1 = Object.assign(
  // Top-level PlasmicCalendarPage1 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    calendarPage1: makeNodeComponent("calendarPage1"),
    search: makeNodeComponent("search"),
    dropdown: makeNodeComponent("dropdown"),
    outlineBg: makeNodeComponent("outlineBg"),
    background0Dp: makeNodeComponent("background0Dp"),
    cardBg: makeNodeComponent("cardBg"),
    placeholder: makeNodeComponent("placeholder"),
    placeholder2: makeNodeComponent("placeholder2"),
    caption: makeNodeComponent("caption"),
    caption2: makeNodeComponent("caption2"),
    chevronDown: makeNodeComponent("chevronDown"),
    dropdown2: makeNodeComponent("dropdown2"),
    outlineBg2: makeNodeComponent("outlineBg2"),
    background0Dp2: makeNodeComponent("background0Dp2"),
    cardBg2: makeNodeComponent("cardBg2"),
    placeholder3: makeNodeComponent("placeholder3"),
    placeholder4: makeNodeComponent("placeholder4"),
    caption3: makeNodeComponent("caption3"),
    caption4: makeNodeComponent("caption4"),
    _28304011: makeNodeComponent("_28304011"),
    outlineBg3: makeNodeComponent("outlineBg3"),
    outlineBg4: makeNodeComponent("outlineBg4"),
    placeholder5: makeNodeComponent("placeholder5"),
    placeholder6: makeNodeComponent("placeholder6"),
    placeholder7: makeNodeComponent("placeholder7"),
    placeholder8: makeNodeComponent("placeholder8"),
    cardBg3: makeNodeComponent("cardBg3"),
    calendar: makeNodeComponent("calendar"),
    background0Dp3: makeNodeComponent("background0Dp3"),
    cardBg4: makeNodeComponent("cardBg4"),
    selector: makeNodeComponent("selector"),
    selector2: makeNodeComponent("selector2"),
    rectangle2: makeNodeComponent("rectangle2"),
    selector3: makeNodeComponent("selector3"),
    rectangle3: makeNodeComponent("rectangle3"),
    selector4: makeNodeComponent("selector4"),
    rectangle4: makeNodeComponent("rectangle4"),
    selector5: makeNodeComponent("selector5"),
    rectangle5: makeNodeComponent("rectangle5"),
    calendar2: makeNodeComponent("calendar2"),
    date: makeNodeComponent("date"),
    _1Second: makeNodeComponent("_1Second"),
    number: makeNodeComponent("number"),
    _31: makeNodeComponent("_31"),
    number2: makeNodeComponent("number2"),
    _30Second: makeNodeComponent("_30Second"),
    number3: makeNodeComponent("number3"),
    _29Second: makeNodeComponent("_29Second"),
    number4: makeNodeComponent("number4"),
    _28Second: makeNodeComponent("_28Second"),
    number5: makeNodeComponent("number5"),
    _27: makeNodeComponent("_27"),
    number6: makeNodeComponent("number6"),
    _26: makeNodeComponent("_26"),
    number7: makeNodeComponent("number7"),
    _25: makeNodeComponent("_25"),
    number8: makeNodeComponent("number8"),
    _24: makeNodeComponent("_24"),
    number9: makeNodeComponent("number9"),
    _23: makeNodeComponent("_23"),
    number10: makeNodeComponent("number10"),
    _22: makeNodeComponent("_22"),
    number11: makeNodeComponent("number11"),
    _20: makeNodeComponent("_20"),
    number12: makeNodeComponent("number12"),
    _19: makeNodeComponent("_19"),
    number13: makeNodeComponent("number13"),
    _18: makeNodeComponent("_18"),
    number14: makeNodeComponent("number14"),
    _17: makeNodeComponent("_17"),
    number15: makeNodeComponent("number15"),
    _16: makeNodeComponent("_16"),
    number16: makeNodeComponent("number16"),
    _15: makeNodeComponent("_15"),
    number17: makeNodeComponent("number17"),
    _14: makeNodeComponent("_14"),
    number18: makeNodeComponent("number18"),
    _13: makeNodeComponent("_13"),
    number19: makeNodeComponent("number19"),
    _12: makeNodeComponent("_12"),
    number20: makeNodeComponent("number20"),
    _11: makeNodeComponent("_11"),
    number21: makeNodeComponent("number21"),
    _10: makeNodeComponent("_10"),
    number22: makeNodeComponent("number22"),
    _9: makeNodeComponent("_9"),
    number23: makeNodeComponent("number23"),
    _8: makeNodeComponent("_8"),
    number24: makeNodeComponent("number24"),
    _7: makeNodeComponent("_7"),
    number25: makeNodeComponent("number25"),
    _6: makeNodeComponent("_6"),
    number26: makeNodeComponent("number26"),
    _5: makeNodeComponent("_5"),
    number27: makeNodeComponent("number27"),
    _4: makeNodeComponent("_4"),
    number28: makeNodeComponent("number28"),
    _3: makeNodeComponent("_3"),
    number29: makeNodeComponent("number29"),
    _2: makeNodeComponent("_2"),
    img: makeNodeComponent("img"),
    number30: makeNodeComponent("number30"),
    numeral: makeNodeComponent("numeral"),
    number31: makeNodeComponent("number31"),
    _30First: makeNodeComponent("_30First"),
    number32: makeNodeComponent("number32"),
    _29First: makeNodeComponent("_29First"),
    number33: makeNodeComponent("number33"),
    _28First: makeNodeComponent("_28First"),
    number34: makeNodeComponent("number34"),
    _32: makeNodeComponent("_32"),
    number35: makeNodeComponent("number35"),
    daysOfTheWeek: makeNodeComponent("daysOfTheWeek"),
    sat: makeNodeComponent("sat"),
    fri: makeNodeComponent("fri"),
    thu: makeNodeComponent("thu"),
    wed: makeNodeComponent("wed"),
    tue: makeNodeComponent("tue"),
    mon: makeNodeComponent("mon"),
    sun: makeNodeComponent("sun"),
    buttonOutlineXs: makeNodeComponent("buttonOutlineXs"),
    buttonBg: makeNodeComponent("buttonBg"),
    caption5: makeNodeComponent("caption5"),
    caption6: makeNodeComponent("caption6"),
    left: makeNodeComponent("left"),
    right: makeNodeComponent("right"),
    segmented: makeNodeComponent("segmented"),
    background0Dp4: makeNodeComponent("background0Dp4"),
    cardBg5: makeNodeComponent("cardBg5"),
    buttonLightXs: makeNodeComponent("buttonLightXs"),
    buttonBg2: makeNodeComponent("buttonBg2"),
    caption7: makeNodeComponent("caption7"),
    caption8: makeNodeComponent("caption8"),
    left2: makeNodeComponent("left2"),
    right2: makeNodeComponent("right2"),
    buttonOutlineXs2: makeNodeComponent("buttonOutlineXs2"),
    buttonBg3: makeNodeComponent("buttonBg3"),
    caption9: makeNodeComponent("caption9"),
    caption10: makeNodeComponent("caption10"),
    left3: makeNodeComponent("left3"),
    right3: makeNodeComponent("right3"),
    h3: makeNodeComponent("h3"),
    subcaption: makeNodeComponent("subcaption"),
    h6: makeNodeComponent("h6"),
    h62: makeNodeComponent("h62"),
    loginBtn: makeNodeComponent("loginBtn"),
    rectangle: makeNodeComponent("rectangle"),
    // Metadata about props expected for PlasmicCalendarPage1
    internalVariantProps: PlasmicCalendarPage1__VariantProps,
    internalArgProps: PlasmicCalendarPage1__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCalendarPage1;
/* prettier-ignore-end */
