// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ivhpgazgw15hPKwKsPQEWr
// Component: WRO27CV0Sj4U
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_game_schedule.module.css"; // plasmic-import: ivhpgazgw15hPKwKsPQEWr/projectcss
import sty from "./PlasmicLandingPage.module.css"; // plasmic-import: WRO27CV0Sj4U/css
import Vector1StrokeIcon from "./icons/PlasmicIcon__Vector1Stroke"; // plasmic-import: dd_eaW0X0s/icon
import SocialIcon from "./icons/PlasmicIcon__Social"; // plasmic-import: 30NfKzi4H_/icon
import Ellipse6Icon from "./icons/PlasmicIcon__Ellipse6"; // plasmic-import: Wf55B7KAcY/icon
import Ellipse7Icon from "./icons/PlasmicIcon__Ellipse7"; // plasmic-import: WhdZmty-yz/icon
import Ellipse5Icon from "./icons/PlasmicIcon__Ellipse5"; // plasmic-import: mhDhYsT-Sx/icon
import Ellipse4Icon from "./icons/PlasmicIcon__Ellipse4"; // plasmic-import: SM8kv9wd81/icon
import Vector1Stroke2Icon from "./icons/PlasmicIcon__Vector1Stroke2"; // plasmic-import: ePB2tCQ5uW/icon
import Ellipse8Icon from "./icons/PlasmicIcon__Ellipse8"; // plasmic-import: ISk7J1ZEms5/icon
import Vector1Stroke3Icon from "./icons/PlasmicIcon__Vector1Stroke3"; // plasmic-import: -xDb8fKqBYH/icon
import Vector1Stroke4Icon from "./icons/PlasmicIcon__Vector1Stroke4"; // plasmic-import: DzqyvHh9hmS/icon
import Ellipse9Icon from "./icons/PlasmicIcon__Ellipse9"; // plasmic-import: fAmMWU690ru/icon
import Ellipse10Icon from "./icons/PlasmicIcon__Ellipse10"; // plasmic-import: FxVkCwo2o-9/icon
import Ellipse11Icon from "./icons/PlasmicIcon__Ellipse11"; // plasmic-import: 4RYjsRgFA0D/icon
import Ellipse12Icon from "./icons/PlasmicIcon__Ellipse12"; // plasmic-import: krBYBGnuI7M/icon
import Ellipse13Icon from "./icons/PlasmicIcon__Ellipse13"; // plasmic-import: TUucQzfwsSD/icon
import Ellipse14Icon from "./icons/PlasmicIcon__Ellipse14"; // plasmic-import: 4dmmYkUIT3L/icon

export const PlasmicLandingPage__VariantProps = new Array();

export const PlasmicLandingPage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicLandingPage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"landingPage"}
            data-plasmic-override={overrides.landingPage}
            className={classNames(projectcss.all, sty.landingPage)}
          >
            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <div
                data-plasmic-name={"bottom"}
                data-plasmic-override={overrides.bottom}
                className={classNames(projectcss.all, sty.bottom)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jyh28
                  )}
                >
                  {"© Copyright 2022 GameSchedule"}
                </div>
              </div>
              <div
                data-plasmic-name={"right"}
                data-plasmic-override={overrides.right}
                className={classNames(projectcss.all, sty.right)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8L5Gx
                  )}
                >
                  {"About\nTerms\nLegal"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wQ1Tk
                  )}
                >
                  {"Press\nSupport"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__t5B0L
                  )}
                >
                  {"Twitter\nInstagram"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__puzSf
                  )}
                >
                  {"About"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rrsNh
                  )}
                >
                  {"Contact"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qdCb3
                  )}
                >
                  {"Social"}
                </div>
              </div>
              <div
                data-plasmic-name={"left"}
                data-plasmic-override={overrides.left}
                className={classNames(projectcss.all, sty.left)}
              >
                <div
                  data-plasmic-name={"logo"}
                  data-plasmic-override={overrides.logo}
                  className={classNames(projectcss.all, sty.logo)}
                >
                  <Vector1StrokeIcon
                    className={classNames(projectcss.all, sty.svg__rFD4)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"nftlanding"}
                    data-plasmic-override={overrides.nftlanding}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.nftlanding
                    )}
                  >
                    {"gameschedule"}
                  </div>
                </div>
                <SocialIcon
                  className={classNames(projectcss.all, sty.svg__sNwh8)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"divider"}
                data-plasmic-override={overrides.divider}
                className={classNames(projectcss.all, sty.divider)}
              >
                <div
                  data-plasmic-name={"rectangle9"}
                  data-plasmic-override={overrides.rectangle9}
                  className={classNames(projectcss.all, sty.rectangle9)}
                />
              </div>
            </div>
            <div
              data-plasmic-name={"upsell"}
              data-plasmic-override={overrides.upsell}
              className={classNames(projectcss.all, sty.upsell)}
            >
              <div
                data-plasmic-name={"background"}
                data-plasmic-override={overrides.background}
                className={classNames(projectcss.all, sty.background)}
              >
                <Ellipse6Icon
                  className={classNames(projectcss.all, sty.svg__bxGsl)}
                  role={"img"}
                />

                <Ellipse7Icon
                  className={classNames(projectcss.all, sty.svg__bBXt)}
                  role={"img"}
                />

                <Ellipse5Icon
                  className={classNames(projectcss.all, sty.svg__jfBi)}
                  role={"img"}
                />

                <Ellipse4Icon
                  className={classNames(projectcss.all, sty.svg__g916X)}
                  role={"img"}
                />
              </div>
              {false ? (
                <div className={classNames(projectcss.all, sty.freeBox__ies30)}>
                  <div
                    data-plasmic-name={"gameSchedule"}
                    data-plasmic-override={overrides.gameSchedule}
                    className={classNames(projectcss.all, sty.gameSchedule)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wnvT
                      )}
                    >
                      {"GameSchedule"}
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mba0X
                    )}
                  >
                    {"Sign up today!"}
                  </div>
                </div>
              ) : null}
              <div
                data-plasmic-name={"icon"}
                data-plasmic-override={overrides.icon}
                className={classNames(projectcss.all, sty.icon)}
              >
                <div
                  data-plasmic-name={"rectangle6"}
                  data-plasmic-override={overrides.rectangle6}
                  className={classNames(projectcss.all, sty.rectangle6)}
                />

                <Vector1Stroke2Icon
                  className={classNames(projectcss.all, sty.svg__vt6Eh)}
                  role={"img"}
                />

                <Ellipse8Icon
                  className={classNames(projectcss.all, sty.svg__pDj1F)}
                  role={"img"}
                />
              </div>
            </div>
            <Vector1Stroke3Icon
              className={classNames(projectcss.all, sty.svg__rcpzo)}
              role={"img"}
            />

            <div
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(projectcss.all, sty.header)}
            >
              <div
                data-plasmic-name={"logo2"}
                data-plasmic-override={overrides.logo2}
                className={classNames(projectcss.all, sty.logo2)}
              >
                <Vector1Stroke4Icon
                  className={classNames(projectcss.all, sty.svg__gqho5)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"nftlanding2"}
                  data-plasmic-override={overrides.nftlanding2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.nftlanding2
                  )}
                >
                  {"gameschedule"}
                </div>
              </div>
              <p.Stack
                as={"div"}
                data-plasmic-name={"navigation"}
                data-plasmic-override={overrides.navigation}
                hasGap={true}
                className={classNames(projectcss.all, sty.navigation)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9PauE
                  )}
                >
                  {"Features"}
                </div>
                <a
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___6C2O
                  )}
                  href={`/new-page-3`}
                >
                  {"About"}
                </a>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__crV6S
                  )}
                >
                  {"Launch"}
                </div>
                <a
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__pgexI
                  )}
                  href={`/new-page`}
                >
                  {"Sign Up"}
                </a>
              </p.Stack>
            </div>
            <div
              data-plasmic-name={"hero"}
              data-plasmic-override={overrides.hero}
              className={classNames(projectcss.all, sty.hero)}
            >
              <div
                data-plasmic-name={"text2"}
                data-plasmic-override={overrides.text2}
                className={classNames(projectcss.all, sty.text2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__w7Ao5
                  )}
                >
                  {"A Game Scheduling Platform  Like No Other"}
                </div>
                {false ? (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5TicI
                    )}
                  >
                    {"Launching Soon"}
                  </div>
                ) : null}
                <div
                  data-plasmic-name={"weMakeSureEveryoneGetsAGame"}
                  data-plasmic-override={overrides.weMakeSureEveryoneGetsAGame}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.weMakeSureEveryoneGetsAGame
                  )}
                >
                  {
                    "We make sure everyone gets to play games with their allocated time."
                  }
                </div>
                <div
                  data-plasmic-name={"cta"}
                  data-plasmic-override={overrides.cta}
                  className={classNames(projectcss.all, sty.cta)}
                >
                  <div
                    data-plasmic-name={"group1"}
                    data-plasmic-override={overrides.group1}
                    className={classNames(projectcss.all, sty.group1)}
                  >
                    <Ellipse9Icon
                      className={classNames(projectcss.all, sty.svg__kwcBj)}
                      role={"img"}
                    />

                    <Ellipse10Icon
                      className={classNames(projectcss.all, sty.svg__xip89)}
                      role={"img"}
                    />

                    <Ellipse11Icon
                      className={classNames(projectcss.all, sty.svg__b2Cf3)}
                      role={"img"}
                    />

                    <Ellipse12Icon
                      className={classNames(projectcss.all, sty.svg__omor5)}
                      role={"img"}
                    />
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fLgv2
                    )}
                  >
                    {"Sign Up"}
                  </div>
                </div>
              </div>
              {false ? (
                <div
                  data-plasmic-name={"graphic"}
                  data-plasmic-override={overrides.graphic}
                  className={classNames(projectcss.all, sty.graphic)}
                >
                  <Ellipse13Icon
                    className={classNames(projectcss.all, sty.svg__dPtQs)}
                    role={"img"}
                  />

                  <Ellipse14Icon
                    className={classNames(projectcss.all, sty.svg__kbnh)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={
                      "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
                    }
                    data-plasmic-override={
                      overrides.design82A0Ada5644E4B87Ae4188Faf9684Ea311
                    }
                    className={classNames(
                      projectcss.all,
                      sty.design82A0Ada5644E4B87Ae4188Faf9684Ea311
                    )}
                  />
                </div>
              ) : null}
            </div>
            <div
              data-plasmic-name={"activisionLogoCallOfDutyHub1"}
              data-plasmic-override={overrides.activisionLogoCallOfDutyHub1}
              className={classNames(
                projectcss.all,
                sty.activisionLogoCallOfDutyHub1
              )}
            />

            <div
              data-plasmic-name={"origin1LogoPngTransparent1"}
              data-plasmic-override={overrides.origin1LogoPngTransparent1}
              className={classNames(
                projectcss.all,
                sty.origin1LogoPngTransparent1
              )}
            />

            <div
              data-plasmic-name={"steamIconLogo1"}
              data-plasmic-override={overrides.steamIconLogo1}
              className={classNames(projectcss.all, sty.steamIconLogo1)}
            />

            <div
              data-plasmic-name={"battlenet2021Icon1"}
              data-plasmic-override={overrides.battlenet2021Icon1}
              className={classNames(projectcss.all, sty.battlenet2021Icon1)}
            />

            <div
              data-plasmic-name={"garenaLogo1"}
              data-plasmic-override={overrides.garenaLogo1}
              className={classNames(projectcss.all, sty.garenaLogo1)}
            />

            <div
              data-plasmic-name={"rectangle29"}
              data-plasmic-override={overrides.rectangle29}
              className={classNames(projectcss.all, sty.rectangle29)}
            />

            <div
              data-plasmic-name={"rectangle30"}
              data-plasmic-override={overrides.rectangle30}
              className={classNames(projectcss.all, sty.rectangle30)}
            />

            <div
              data-plasmic-name={"h2X1NSwitchDsApexLegendsSeasonBanner1"}
              data-plasmic-override={
                overrides.h2X1NSwitchDsApexLegendsSeasonBanner1
              }
              className={classNames(
                projectcss.all,
                sty.h2X1NSwitchDsApexLegendsSeasonBanner1
              )}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__g2QwN
              )}
            >
              {"UPCOMING"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kZbGj
              )}
            >
              {"UPCOMING"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__gXBm
              )}
            >
              {"22 May 2022"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__plgHj
              )}
            >
              {"1 Day left"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__fGeJd
              )}
            >
              {"UPCOMING"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__zNpo
              )}
            >
              {"UPCOMING"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__yc6Fm
              )}
            >
              {"apex legends"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__f4Sgm
              )}
            >
              {"22 May 2022"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mobNb
              )}
            >
              {"1 Day left"}
            </div>
            <div
              data-plasmic-name={"rectangle31"}
              data-plasmic-override={overrides.rectangle31}
              className={classNames(projectcss.all, sty.rectangle31)}
            />

            <div
              data-plasmic-name={"rectangle32"}
              data-plasmic-override={overrides.rectangle32}
              className={classNames(projectcss.all, sty.rectangle32)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__t6Ice
              )}
            >
              {"fifa 22"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___2TLi6
              )}
            >
              {"UPCOMING"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___0RJca
              )}
            >
              {"UPCOMING"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jYasb
              )}
            >
              {"22 May 2022"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__op3L
              )}
            >
              {"1 Day left"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__oYgv1
              )}
            >
              {"UPCOMING"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xqnUy
              )}
            >
              {"UPCOMING"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ssM2X
              )}
            >
              {"22 May 2022"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bZs1T
              )}
            >
              {"1 Day left"}
            </div>
            <div
              data-plasmic-name={"fifa22Cover1"}
              data-plasmic-override={overrides.fifa22Cover1}
              className={classNames(projectcss.all, sty.fifa22Cover1)}
            />

            <div
              data-plasmic-name={"rectangle33"}
              data-plasmic-override={overrides.rectangle33}
              className={classNames(projectcss.all, sty.rectangle33)}
            />

            <div
              data-plasmic-name={"rectangle34"}
              data-plasmic-override={overrides.rectangle34}
              className={classNames(projectcss.all, sty.rectangle34)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__aLg5
              )}
            >
              {"UPCOMING"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tyK3J
              )}
            >
              {"UPCOMING"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___74JYf
              )}
            >
              {"22 May 2022"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__laczB
              )}
            >
              {"1 Day left"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__s3JBs
              )}
            >
              {"UPCOMING"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__i4Oy
              )}
            >
              {"UPCOMING"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xmNb7
              )}
            >
              {"22 May 2022"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__dFfng
              )}
            >
              {"1 Day left"}
            </div>
            <div
              data-plasmic-name={"fifa22Cover2"}
              data-plasmic-override={overrides.fifa22Cover2}
              className={classNames(projectcss.all, sty.fifa22Cover2)}
            />

            <div
              data-plasmic-name={"battlefield2042CoverArt1"}
              data-plasmic-override={overrides.battlefield2042CoverArt1}
              className={classNames(
                projectcss.all,
                sty.battlefield2042CoverArt1
              )}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xEfzU
              )}
            >
              {"battlefield 2042"}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "landingPage",
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9",
    "upsell",
    "background",
    "gameSchedule",
    "icon",
    "rectangle6",
    "header",
    "logo2",
    "nftlanding2",
    "navigation",
    "hero",
    "text2",
    "weMakeSureEveryoneGetsAGame",
    "cta",
    "group1",
    "graphic",
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311",
    "activisionLogoCallOfDutyHub1",
    "origin1LogoPngTransparent1",
    "steamIconLogo1",
    "battlenet2021Icon1",
    "garenaLogo1",
    "rectangle29",
    "rectangle30",
    "h2X1NSwitchDsApexLegendsSeasonBanner1",
    "rectangle31",
    "rectangle32",
    "fifa22Cover1",
    "rectangle33",
    "rectangle34",
    "fifa22Cover2",
    "battlefield2042CoverArt1"
  ],

  landingPage: [
    "landingPage",
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9",
    "upsell",
    "background",
    "gameSchedule",
    "icon",
    "rectangle6",
    "header",
    "logo2",
    "nftlanding2",
    "navigation",
    "hero",
    "text2",
    "weMakeSureEveryoneGetsAGame",
    "cta",
    "group1",
    "graphic",
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311",
    "activisionLogoCallOfDutyHub1",
    "origin1LogoPngTransparent1",
    "steamIconLogo1",
    "battlenet2021Icon1",
    "garenaLogo1",
    "rectangle29",
    "rectangle30",
    "h2X1NSwitchDsApexLegendsSeasonBanner1",
    "rectangle31",
    "rectangle32",
    "fifa22Cover1",
    "rectangle33",
    "rectangle34",
    "fifa22Cover2",
    "battlefield2042CoverArt1"
  ],

  footer: [
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9"
  ],

  bottom: ["bottom"],
  right: ["right"],
  left: ["left", "logo", "nftlanding"],
  logo: ["logo", "nftlanding"],
  nftlanding: ["nftlanding"],
  divider: ["divider", "rectangle9"],
  rectangle9: ["rectangle9"],
  upsell: ["upsell", "background", "gameSchedule", "icon", "rectangle6"],
  background: ["background"],
  gameSchedule: ["gameSchedule"],
  icon: ["icon", "rectangle6"],
  rectangle6: ["rectangle6"],
  header: ["header", "logo2", "nftlanding2", "navigation"],
  logo2: ["logo2", "nftlanding2"],
  nftlanding2: ["nftlanding2"],
  navigation: ["navigation"],
  hero: [
    "hero",
    "text2",
    "weMakeSureEveryoneGetsAGame",
    "cta",
    "group1",
    "graphic",
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
  ],

  text2: ["text2", "weMakeSureEveryoneGetsAGame", "cta", "group1"],
  weMakeSureEveryoneGetsAGame: ["weMakeSureEveryoneGetsAGame"],
  cta: ["cta", "group1"],
  group1: ["group1"],
  graphic: ["graphic", "design82A0Ada5644E4B87Ae4188Faf9684Ea311"],
  design82A0Ada5644E4B87Ae4188Faf9684Ea311: [
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
  ],

  activisionLogoCallOfDutyHub1: ["activisionLogoCallOfDutyHub1"],
  origin1LogoPngTransparent1: ["origin1LogoPngTransparent1"],
  steamIconLogo1: ["steamIconLogo1"],
  battlenet2021Icon1: ["battlenet2021Icon1"],
  garenaLogo1: ["garenaLogo1"],
  rectangle29: ["rectangle29"],
  rectangle30: ["rectangle30"],
  h2X1NSwitchDsApexLegendsSeasonBanner1: [
    "h2X1NSwitchDsApexLegendsSeasonBanner1"
  ],

  rectangle31: ["rectangle31"],
  rectangle32: ["rectangle32"],
  fifa22Cover1: ["fifa22Cover1"],
  rectangle33: ["rectangle33"],
  rectangle34: ["rectangle34"],
  fifa22Cover2: ["fifa22Cover2"],
  battlefield2042CoverArt1: ["battlefield2042CoverArt1"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLandingPage__ArgProps,
          internalVariantPropNames: PlasmicLandingPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLandingPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLandingPage";
  } else {
    func.displayName = `PlasmicLandingPage.${nodeName}`;
  }
  return func;
}

export const PlasmicLandingPage = Object.assign(
  // Top-level PlasmicLandingPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    landingPage: makeNodeComponent("landingPage"),
    footer: makeNodeComponent("footer"),
    bottom: makeNodeComponent("bottom"),
    right: makeNodeComponent("right"),
    left: makeNodeComponent("left"),
    logo: makeNodeComponent("logo"),
    nftlanding: makeNodeComponent("nftlanding"),
    divider: makeNodeComponent("divider"),
    rectangle9: makeNodeComponent("rectangle9"),
    upsell: makeNodeComponent("upsell"),
    background: makeNodeComponent("background"),
    gameSchedule: makeNodeComponent("gameSchedule"),
    icon: makeNodeComponent("icon"),
    rectangle6: makeNodeComponent("rectangle6"),
    header: makeNodeComponent("header"),
    logo2: makeNodeComponent("logo2"),
    nftlanding2: makeNodeComponent("nftlanding2"),
    navigation: makeNodeComponent("navigation"),
    hero: makeNodeComponent("hero"),
    text2: makeNodeComponent("text2"),
    weMakeSureEveryoneGetsAGame: makeNodeComponent(
      "weMakeSureEveryoneGetsAGame"
    ),
    cta: makeNodeComponent("cta"),
    group1: makeNodeComponent("group1"),
    graphic: makeNodeComponent("graphic"),
    design82A0Ada5644E4B87Ae4188Faf9684Ea311: makeNodeComponent(
      "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
    ),
    activisionLogoCallOfDutyHub1: makeNodeComponent(
      "activisionLogoCallOfDutyHub1"
    ),
    origin1LogoPngTransparent1: makeNodeComponent("origin1LogoPngTransparent1"),
    steamIconLogo1: makeNodeComponent("steamIconLogo1"),
    battlenet2021Icon1: makeNodeComponent("battlenet2021Icon1"),
    garenaLogo1: makeNodeComponent("garenaLogo1"),
    rectangle29: makeNodeComponent("rectangle29"),
    rectangle30: makeNodeComponent("rectangle30"),
    h2X1NSwitchDsApexLegendsSeasonBanner1: makeNodeComponent(
      "h2X1NSwitchDsApexLegendsSeasonBanner1"
    ),
    rectangle31: makeNodeComponent("rectangle31"),
    rectangle32: makeNodeComponent("rectangle32"),
    fifa22Cover1: makeNodeComponent("fifa22Cover1"),
    rectangle33: makeNodeComponent("rectangle33"),
    rectangle34: makeNodeComponent("rectangle34"),
    fifa22Cover2: makeNodeComponent("fifa22Cover2"),
    battlefield2042CoverArt1: makeNodeComponent("battlefield2042CoverArt1"),
    // Metadata about props expected for PlasmicLandingPage
    internalVariantProps: PlasmicLandingPage__VariantProps,
    internalArgProps: PlasmicLandingPage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicLandingPage;
/* prettier-ignore-end */
