// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ivhpgazgw15hPKwKsPQEWr
// Component: UmjHCA6DKu
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_game_schedule.module.css"; // plasmic-import: ivhpgazgw15hPKwKsPQEWr/projectcss
import sty from "./PlasmicSupportPage.module.css"; // plasmic-import: UmjHCA6DKu/css
import Vector1StrokeIcon from "./icons/PlasmicIcon__Vector1Stroke"; // plasmic-import: dd_eaW0X0s/icon
import SocialIcon from "./icons/PlasmicIcon__Social"; // plasmic-import: 30NfKzi4H_/icon
import Vector1Stroke4Icon from "./icons/PlasmicIcon__Vector1Stroke4"; // plasmic-import: DzqyvHh9hmS/icon
import Ellipse21Icon from "./icons/PlasmicIcon__Ellipse21"; // plasmic-import: aa16QWTue/icon
import Ellipse22Icon from "./icons/PlasmicIcon__Ellipse22"; // plasmic-import: Mgsooamc2m/icon
import Vector1Stroke3Icon from "./icons/PlasmicIcon__Vector1Stroke3"; // plasmic-import: -xDb8fKqBYH/icon

export const PlasmicSupportPage__VariantProps = new Array();

export const PlasmicSupportPage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicSupportPage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"supportPage"}
            data-plasmic-override={overrides.supportPage}
            className={classNames(projectcss.all, sty.supportPage)}
          >
            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <div
                data-plasmic-name={"bottom"}
                data-plasmic-override={overrides.bottom}
                className={classNames(projectcss.all, sty.bottom)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nhpj
                  )}
                >
                  {"© Copyright 2022 GameSchedule"}
                </div>
              </div>
              <div
                data-plasmic-name={"right"}
                data-plasmic-override={overrides.right}
                className={classNames(projectcss.all, sty.right)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__m9VPa
                  )}
                >
                  {"About\nTerms\nLegal"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7U1P
                  )}
                >
                  {"Press\nSupport"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y87Da
                  )}
                >
                  {"Twitter\nInstagram"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dlsVs
                  )}
                >
                  {"About"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ao7X5
                  )}
                >
                  {"Contact"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3D0Br
                  )}
                >
                  {"Social"}
                </div>
              </div>
              <div
                data-plasmic-name={"left"}
                data-plasmic-override={overrides.left}
                className={classNames(projectcss.all, sty.left)}
              >
                <div
                  data-plasmic-name={"logo"}
                  data-plasmic-override={overrides.logo}
                  className={classNames(projectcss.all, sty.logo)}
                >
                  <Vector1StrokeIcon
                    className={classNames(projectcss.all, sty.svg__nhgqP)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"nftlanding"}
                    data-plasmic-override={overrides.nftlanding}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.nftlanding
                    )}
                  >
                    {"gameschedule"}
                  </div>
                </div>
                <SocialIcon
                  className={classNames(projectcss.all, sty.svg__jc66I)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"divider"}
                data-plasmic-override={overrides.divider}
                className={classNames(projectcss.all, sty.divider)}
              >
                <div
                  data-plasmic-name={"rectangle9"}
                  data-plasmic-override={overrides.rectangle9}
                  className={classNames(projectcss.all, sty.rectangle9)}
                />
              </div>
            </div>
            <div
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(projectcss.all, sty.header)}
            >
              <div
                data-plasmic-name={"logo2"}
                data-plasmic-override={overrides.logo2}
                className={classNames(projectcss.all, sty.logo2)}
              >
                <Vector1Stroke4Icon
                  className={classNames(projectcss.all, sty.svg__c8XTt)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"nftlanding2"}
                  data-plasmic-override={overrides.nftlanding2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.nftlanding2
                  )}
                >
                  {"gameschedule"}
                </div>
              </div>
              <p.Stack
                as={"div"}
                data-plasmic-name={"navigation"}
                data-plasmic-override={overrides.navigation}
                hasGap={true}
                className={classNames(projectcss.all, sty.navigation)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ffLlZ
                  )}
                >
                  {"Features"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yBU1
                  )}
                >
                  {"About"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rns3F
                  )}
                >
                  {"Launch"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fwnzN
                  )}
                >
                  {"Sign Up"}
                </div>
              </p.Stack>
            </div>
            <div
              data-plasmic-name={"password"}
              data-plasmic-override={overrides.password}
              className={classNames(projectcss.all, sty.password)}
            >
              <div
                data-plasmic-name={"rectangle"}
                data-plasmic-override={overrides.rectangle}
                className={classNames(projectcss.all, sty.rectangle)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qAy7
                )}
              >
                {"First Name"}
              </div>
            </div>
            <div
              data-plasmic-name={"password2"}
              data-plasmic-override={overrides.password2}
              className={classNames(projectcss.all, sty.password2)}
            >
              <div
                data-plasmic-name={"rectangle2"}
                data-plasmic-override={overrides.rectangle2}
                className={classNames(projectcss.all, sty.rectangle2)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tXa22
                )}
              >
                {"Last Name"}
              </div>
            </div>
            <div
              data-plasmic-name={"password3"}
              data-plasmic-override={overrides.password3}
              className={classNames(projectcss.all, sty.password3)}
            >
              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(projectcss.all, sty.rectangle3)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2Ghte
                )}
              >
                {"What can we do for you?"}
              </div>
            </div>
            <div
              data-plasmic-name={"username"}
              data-plasmic-override={overrides.username}
              className={classNames(projectcss.all, sty.username)}
            >
              <div
                data-plasmic-name={"rectangle4"}
                data-plasmic-override={overrides.rectangle4}
                className={classNames(projectcss.all, sty.rectangle4)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__povAs
                )}
              >
                {"Email"}
              </div>
            </div>
            <div
              data-plasmic-name={"hero"}
              data-plasmic-override={overrides.hero}
              className={classNames(projectcss.all, sty.hero)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__cmSqC)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0LZxw
                  )}
                >
                  {"Contact Us"}
                </div>
                {false ? (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lJ135
                    )}
                  >
                    {"Launching Soon"}
                  </div>
                ) : null}
              </div>
              {false ? (
                <div
                  data-plasmic-name={"graphic"}
                  data-plasmic-override={overrides.graphic}
                  className={classNames(projectcss.all, sty.graphic)}
                >
                  <Ellipse21Icon
                    className={classNames(projectcss.all, sty.svg__f854Q)}
                    role={"img"}
                  />

                  <Ellipse22Icon
                    className={classNames(projectcss.all, sty.svg___7UFmc)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={
                      "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
                    }
                    data-plasmic-override={
                      overrides.design82A0Ada5644E4B87Ae4188Faf9684Ea311
                    }
                    className={classNames(
                      projectcss.all,
                      sty.design82A0Ada5644E4B87Ae4188Faf9684Ea311
                    )}
                  />
                </div>
              ) : null}
            </div>
            <div
              data-plasmic-name={"loginBtn"}
              data-plasmic-override={overrides.loginBtn}
              className={classNames(projectcss.all, sty.loginBtn)}
            >
              <div
                data-plasmic-name={"rectangle5"}
                data-plasmic-override={overrides.rectangle5}
                className={classNames(projectcss.all, sty.rectangle5)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1WhMr
                )}
              >
                {"SEND"}
              </div>
            </div>
            <Vector1Stroke3Icon
              className={classNames(projectcss.all, sty.svg___1OfPu)}
              role={"img"}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "supportPage",
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9",
    "header",
    "logo2",
    "nftlanding2",
    "navigation",
    "password",
    "rectangle",
    "password2",
    "rectangle2",
    "password3",
    "rectangle3",
    "username",
    "rectangle4",
    "hero",
    "graphic",
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311",
    "loginBtn",
    "rectangle5"
  ],

  supportPage: [
    "supportPage",
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9",
    "header",
    "logo2",
    "nftlanding2",
    "navigation",
    "password",
    "rectangle",
    "password2",
    "rectangle2",
    "password3",
    "rectangle3",
    "username",
    "rectangle4",
    "hero",
    "graphic",
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311",
    "loginBtn",
    "rectangle5"
  ],

  footer: [
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9"
  ],

  bottom: ["bottom"],
  right: ["right"],
  left: ["left", "logo", "nftlanding"],
  logo: ["logo", "nftlanding"],
  nftlanding: ["nftlanding"],
  divider: ["divider", "rectangle9"],
  rectangle9: ["rectangle9"],
  header: ["header", "logo2", "nftlanding2", "navigation"],
  logo2: ["logo2", "nftlanding2"],
  nftlanding2: ["nftlanding2"],
  navigation: ["navigation"],
  password: ["password", "rectangle"],
  rectangle: ["rectangle"],
  password2: ["password2", "rectangle2"],
  rectangle2: ["rectangle2"],
  password3: ["password3", "rectangle3"],
  rectangle3: ["rectangle3"],
  username: ["username", "rectangle4"],
  rectangle4: ["rectangle4"],
  hero: ["hero", "graphic", "design82A0Ada5644E4B87Ae4188Faf9684Ea311"],
  graphic: ["graphic", "design82A0Ada5644E4B87Ae4188Faf9684Ea311"],
  design82A0Ada5644E4B87Ae4188Faf9684Ea311: [
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
  ],

  loginBtn: ["loginBtn", "rectangle5"],
  rectangle5: ["rectangle5"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSupportPage__ArgProps,
          internalVariantPropNames: PlasmicSupportPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSupportPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSupportPage";
  } else {
    func.displayName = `PlasmicSupportPage.${nodeName}`;
  }
  return func;
}

export const PlasmicSupportPage = Object.assign(
  // Top-level PlasmicSupportPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    supportPage: makeNodeComponent("supportPage"),
    footer: makeNodeComponent("footer"),
    bottom: makeNodeComponent("bottom"),
    right: makeNodeComponent("right"),
    left: makeNodeComponent("left"),
    logo: makeNodeComponent("logo"),
    nftlanding: makeNodeComponent("nftlanding"),
    divider: makeNodeComponent("divider"),
    rectangle9: makeNodeComponent("rectangle9"),
    header: makeNodeComponent("header"),
    logo2: makeNodeComponent("logo2"),
    nftlanding2: makeNodeComponent("nftlanding2"),
    navigation: makeNodeComponent("navigation"),
    password: makeNodeComponent("password"),
    rectangle: makeNodeComponent("rectangle"),
    password2: makeNodeComponent("password2"),
    rectangle2: makeNodeComponent("rectangle2"),
    password3: makeNodeComponent("password3"),
    rectangle3: makeNodeComponent("rectangle3"),
    username: makeNodeComponent("username"),
    rectangle4: makeNodeComponent("rectangle4"),
    hero: makeNodeComponent("hero"),
    graphic: makeNodeComponent("graphic"),
    design82A0Ada5644E4B87Ae4188Faf9684Ea311: makeNodeComponent(
      "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
    ),
    loginBtn: makeNodeComponent("loginBtn"),
    rectangle5: makeNodeComponent("rectangle5"),
    // Metadata about props expected for PlasmicSupportPage
    internalVariantProps: PlasmicSupportPage__VariantProps,
    internalArgProps: PlasmicSupportPage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSupportPage;
/* prettier-ignore-end */
