// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ivhpgazgw15hPKwKsPQEWr
// Component: 4QRCWYpie3
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_game_schedule.module.css"; // plasmic-import: ivhpgazgw15hPKwKsPQEWr/projectcss
import sty from "./PlasmicProfilePage.module.css"; // plasmic-import: 4QRCWYpie3/css
import Vector1StrokeIcon from "./icons/PlasmicIcon__Vector1Stroke"; // plasmic-import: dd_eaW0X0s/icon
import SocialIcon from "./icons/PlasmicIcon__Social"; // plasmic-import: 30NfKzi4H_/icon
import Vector1Stroke3Icon from "./icons/PlasmicIcon__Vector1Stroke3"; // plasmic-import: -xDb8fKqBYH/icon
import Vector4Icon from "./icons/PlasmicIcon__Vector4"; // plasmic-import: yIURuz5zO/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: z1kTwBx_qd/icon
import Ellipse23Icon from "./icons/PlasmicIcon__Ellipse23"; // plasmic-import: XOTEuvfOhY/icon
import Ellipse24Icon from "./icons/PlasmicIcon__Ellipse24"; // plasmic-import: iRnEvPBgFj/icon
import Group14Icon from "./icons/PlasmicIcon__Group14"; // plasmic-import: -3qk7d9GbP/icon
import Ellipse3Icon from "./icons/PlasmicIcon__Ellipse3"; // plasmic-import: OWpkiYs2yD/icon
import accountBoxN2BExRsS2 from "./images/accountBox.svg"; // plasmic-import: N2b_ExRsS2/picture

export const PlasmicProfilePage__VariantProps = new Array();

export const PlasmicProfilePage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicProfilePage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"profilePage"}
            data-plasmic-override={overrides.profilePage}
            className={classNames(projectcss.all, sty.profilePage)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"sectionSmall"}
              data-plasmic-override={overrides.sectionSmall}
              hasGap={true}
              className={classNames(projectcss.all, sty.sectionSmall)}
            >
              <div
                data-plasmic-name={"icon"}
                data-plasmic-override={overrides.icon}
                className={classNames(projectcss.all, sty.icon)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"image2"}
                    data-plasmic-override={overrides.image2}
                    className={classNames(projectcss.all, sty.image2)}
                  />
                ) : null}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__lm8Y)}>
                {false ? (
                  <div
                    data-plasmic-name={"anNftLikeNoOther"}
                    data-plasmic-override={overrides.anNftLikeNoOther}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.anNftLikeNoOther
                    )}
                  >
                    {"Test"}
                  </div>
                ) : null}
                {false ? (
                  <div
                    data-plasmic-name={
                      "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft"
                    }
                    data-plasmic-override={
                      overrides.dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft
                    )}
                  >
                    {"Test"}
                  </div>
                ) : null}
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              data-plasmic-name={"sectionSmall2"}
              data-plasmic-override={overrides.sectionSmall2}
              hasGap={true}
              className={classNames(projectcss.all, sty.sectionSmall2)}
            >
              <div
                data-plasmic-name={"icon2"}
                data-plasmic-override={overrides.icon2}
                className={classNames(projectcss.all, sty.icon2)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"image3"}
                    data-plasmic-override={overrides.image3}
                    className={classNames(projectcss.all, sty.image3)}
                  />
                ) : null}
              </div>
              <div
                data-plasmic-name={"text2"}
                data-plasmic-override={overrides.text2}
                className={classNames(projectcss.all, sty.text2)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"anNftLikeNoOther2"}
                    data-plasmic-override={overrides.anNftLikeNoOther2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.anNftLikeNoOther2
                    )}
                  >
                    {"Test"}
                  </div>
                ) : null}
                {false ? (
                  <div
                    data-plasmic-name={
                      "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft2"
                    }
                    data-plasmic-override={
                      overrides.dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft2
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft2
                    )}
                  >
                    {"Test"}
                  </div>
                ) : null}
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              data-plasmic-name={"sectionSmall3"}
              data-plasmic-override={overrides.sectionSmall3}
              hasGap={true}
              className={classNames(projectcss.all, sty.sectionSmall3)}
            >
              <div
                data-plasmic-name={"icon3"}
                data-plasmic-override={overrides.icon3}
                className={classNames(projectcss.all, sty.icon3)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"image4"}
                    data-plasmic-override={overrides.image4}
                    className={classNames(projectcss.all, sty.image4)}
                  />
                ) : null}
              </div>
              <div
                data-plasmic-name={"text3"}
                data-plasmic-override={overrides.text3}
                className={classNames(projectcss.all, sty.text3)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"anNftLikeNoOther3"}
                    data-plasmic-override={overrides.anNftLikeNoOther3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.anNftLikeNoOther3
                    )}
                  >
                    {"Test"}
                  </div>
                ) : null}
                {false ? (
                  <div
                    data-plasmic-name={
                      "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft3"
                    }
                    data-plasmic-override={
                      overrides.dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft3
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft3
                    )}
                  >
                    {"Test"}
                  </div>
                ) : null}
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              data-plasmic-name={"sectionSmall4"}
              data-plasmic-override={overrides.sectionSmall4}
              hasGap={true}
              className={classNames(projectcss.all, sty.sectionSmall4)}
            >
              <div
                data-plasmic-name={"icon4"}
                data-plasmic-override={overrides.icon4}
                className={classNames(projectcss.all, sty.icon4)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"image5"}
                    data-plasmic-override={overrides.image5}
                    className={classNames(projectcss.all, sty.image5)}
                  />
                ) : null}
              </div>
              <div
                data-plasmic-name={"text4"}
                data-plasmic-override={overrides.text4}
                className={classNames(projectcss.all, sty.text4)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"anNftLikeNoOther4"}
                    data-plasmic-override={overrides.anNftLikeNoOther4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.anNftLikeNoOther4
                    )}
                  >
                    {"Test"}
                  </div>
                ) : null}
                {false ? (
                  <div
                    data-plasmic-name={
                      "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft4"
                    }
                    data-plasmic-override={
                      overrides.dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft4
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft4
                    )}
                  >
                    {"Test"}
                  </div>
                ) : null}
              </div>
            </p.Stack>
            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <div
                data-plasmic-name={"bottom"}
                data-plasmic-override={overrides.bottom}
                className={classNames(projectcss.all, sty.bottom)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fZw6V
                  )}
                >
                  {"© Copyright 2022 GameSchedule"}
                </div>
              </div>
              <div
                data-plasmic-name={"right"}
                data-plasmic-override={overrides.right}
                className={classNames(projectcss.all, sty.right)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tmvXu
                  )}
                >
                  {"About\nTerms\nLegal"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jlIBz
                  )}
                >
                  {"Press\nSupport"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___33Lxm
                  )}
                >
                  {"Twitter\nInstagram"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nn0Rx
                  )}
                >
                  {"About"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__duwiq
                  )}
                >
                  {"Contact"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zgIc
                  )}
                >
                  {"Social"}
                </div>
              </div>
              <div
                data-plasmic-name={"left"}
                data-plasmic-override={overrides.left}
                className={classNames(projectcss.all, sty.left)}
              >
                <div
                  data-plasmic-name={"logo"}
                  data-plasmic-override={overrides.logo}
                  className={classNames(projectcss.all, sty.logo)}
                >
                  <Vector1StrokeIcon
                    className={classNames(projectcss.all, sty.svg__xG32D)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"nftlanding"}
                    data-plasmic-override={overrides.nftlanding}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.nftlanding
                    )}
                  >
                    {"gameschedule"}
                  </div>
                </div>
                <SocialIcon
                  className={classNames(projectcss.all, sty.svg__qzTd4)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"divider"}
                data-plasmic-override={overrides.divider}
                className={classNames(projectcss.all, sty.divider)}
              >
                <div
                  data-plasmic-name={"rectangle9"}
                  data-plasmic-override={overrides.rectangle9}
                  className={classNames(projectcss.all, sty.rectangle9)}
                />
              </div>
            </div>
            <Vector1Stroke3Icon
              className={classNames(projectcss.all, sty.svg__qYyJ8)}
              role={"img"}
            />

            <Vector4Icon
              className={classNames(projectcss.all, sty.svg__zYFs)}
              role={"img"}
            />

            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__gBkG)}
              role={"img"}
            />

            <p.PlasmicImg
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"24px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"24px"}
              loading={"lazy"}
              src={{
                src: accountBoxN2BExRsS2,
                fullWidth: 24,
                fullHeight: 24,
                aspectRatio: 1
              }}
            />

            <div
              data-plasmic-name={"call"}
              data-plasmic-override={overrides.call}
              className={classNames(projectcss.all, sty.call)}
            />

            <div
              data-plasmic-name={"hero"}
              data-plasmic-override={overrides.hero}
              className={classNames(projectcss.all, sty.hero)}
            >
              <div
                data-plasmic-name={"text5"}
                data-plasmic-override={overrides.text5}
                className={classNames(projectcss.all, sty.text5)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3EZx4
                  )}
                >
                  {"User Settings"}
                </div>
                {false ? (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mGr4J
                    )}
                  >
                    {"Launching Soon"}
                  </div>
                ) : null}
              </div>
              {false ? (
                <div
                  data-plasmic-name={"graphic"}
                  data-plasmic-override={overrides.graphic}
                  className={classNames(projectcss.all, sty.graphic)}
                >
                  <Ellipse23Icon
                    className={classNames(projectcss.all, sty.svg__h7ADb)}
                    role={"img"}
                  />

                  <Ellipse24Icon
                    className={classNames(projectcss.all, sty.svg__p4O3)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={
                      "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
                    }
                    data-plasmic-override={
                      overrides.design82A0Ada5644E4B87Ae4188Faf9684Ea311
                    }
                    className={classNames(
                      projectcss.all,
                      sty.design82A0Ada5644E4B87Ae4188Faf9684Ea311
                    )}
                  />
                </div>
              ) : null}
            </div>
            <div
              data-plasmic-name={"group32"}
              data-plasmic-override={overrides.group32}
              className={classNames(projectcss.all, sty.group32)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ckX0
                )}
              >
                {"Status"}
              </div>
              <Group14Icon
                className={classNames(projectcss.all, sty.svg__yucG6)}
                role={"img"}
              />
            </div>
            <div
              data-plasmic-name={"group31"}
              data-plasmic-override={overrides.group31}
              className={classNames(projectcss.all, sty.group31)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___94WH
                )}
              >
                {"Edit Profile"}
              </div>
              <Group14Icon
                className={classNames(projectcss.all, sty.svg__ozbZh)}
                role={"img"}
              />
            </div>
            <div
              data-plasmic-name={"group30"}
              data-plasmic-override={overrides.group30}
              className={classNames(projectcss.all, sty.group30)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mx6Ia
                )}
              >
                {"Change Password"}
              </div>
              <Group14Icon
                className={classNames(projectcss.all, sty.svg__dy5V)}
                role={"img"}
              />
            </div>
            <div
              data-plasmic-name={"group28"}
              data-plasmic-override={overrides.group28}
              className={classNames(projectcss.all, sty.group28)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__c6JdW
                )}
              >
                {"Push Notifications"}
              </div>
              <div
                data-plasmic-name={"group20"}
                data-plasmic-override={overrides.group20}
                className={classNames(projectcss.all, sty.group20)}
              >
                <div
                  data-plasmic-name={"rectangle28"}
                  data-plasmic-override={overrides.rectangle28}
                  className={classNames(projectcss.all, sty.rectangle28)}
                />

                <Ellipse3Icon
                  className={classNames(projectcss.all, sty.svg__eZdx8)}
                  role={"img"}
                />
              </div>
            </div>
            <p.Stack
              as={"div"}
              data-plasmic-name={"sectionSmall5"}
              data-plasmic-override={overrides.sectionSmall5}
              hasGap={true}
              className={classNames(projectcss.all, sty.sectionSmall5)}
            >
              <div
                data-plasmic-name={"icon5"}
                data-plasmic-override={overrides.icon5}
                className={classNames(projectcss.all, sty.icon5)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"image6"}
                    data-plasmic-override={overrides.image6}
                    className={classNames(projectcss.all, sty.image6)}
                  />
                ) : null}
              </div>
              <div
                data-plasmic-name={"text6"}
                data-plasmic-override={overrides.text6}
                className={classNames(projectcss.all, sty.text6)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"anNftLikeNoOther5"}
                    data-plasmic-override={overrides.anNftLikeNoOther5}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.anNftLikeNoOther5
                    )}
                  >
                    {"Test"}
                  </div>
                ) : null}
                {false ? (
                  <div
                    data-plasmic-name={
                      "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft5"
                    }
                    data-plasmic-override={
                      overrides.dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft5
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft5
                    )}
                  >
                    {"Test"}
                  </div>
                ) : null}
              </div>
            </p.Stack>
            <div
              data-plasmic-name={"group33"}
              data-plasmic-override={overrides.group33}
              className={classNames(projectcss.all, sty.group33)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cUmCo
                )}
              >
                {"Dark Mode"}
              </div>
              <div
                data-plasmic-name={"group21"}
                data-plasmic-override={overrides.group21}
                className={classNames(projectcss.all, sty.group21)}
              >
                <div
                  data-plasmic-name={"rectangle29"}
                  data-plasmic-override={overrides.rectangle29}
                  className={classNames(projectcss.all, sty.rectangle29)}
                />

                <Ellipse3Icon
                  className={classNames(projectcss.all, sty.svg__e706E)}
                  role={"img"}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "profilePage",
    "sectionSmall",
    "icon",
    "image2",
    "anNftLikeNoOther",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft",
    "sectionSmall2",
    "icon2",
    "image3",
    "text2",
    "anNftLikeNoOther2",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft2",
    "sectionSmall3",
    "icon3",
    "image4",
    "text3",
    "anNftLikeNoOther3",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft3",
    "sectionSmall4",
    "icon4",
    "image5",
    "text4",
    "anNftLikeNoOther4",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft4",
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9",
    "img",
    "call",
    "hero",
    "text5",
    "graphic",
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311",
    "group32",
    "group31",
    "group30",
    "group28",
    "group20",
    "rectangle28",
    "sectionSmall5",
    "icon5",
    "image6",
    "text6",
    "anNftLikeNoOther5",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft5",
    "group33",
    "group21",
    "rectangle29"
  ],

  profilePage: [
    "profilePage",
    "sectionSmall",
    "icon",
    "image2",
    "anNftLikeNoOther",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft",
    "sectionSmall2",
    "icon2",
    "image3",
    "text2",
    "anNftLikeNoOther2",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft2",
    "sectionSmall3",
    "icon3",
    "image4",
    "text3",
    "anNftLikeNoOther3",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft3",
    "sectionSmall4",
    "icon4",
    "image5",
    "text4",
    "anNftLikeNoOther4",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft4",
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9",
    "img",
    "call",
    "hero",
    "text5",
    "graphic",
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311",
    "group32",
    "group31",
    "group30",
    "group28",
    "group20",
    "rectangle28",
    "sectionSmall5",
    "icon5",
    "image6",
    "text6",
    "anNftLikeNoOther5",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft5",
    "group33",
    "group21",
    "rectangle29"
  ],

  sectionSmall: [
    "sectionSmall",
    "icon",
    "image2",
    "anNftLikeNoOther",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft"
  ],

  icon: ["icon", "image2"],
  image2: ["image2"],
  anNftLikeNoOther: ["anNftLikeNoOther"],
  dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft:
    [
      "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft"
    ],

  sectionSmall2: [
    "sectionSmall2",
    "icon2",
    "image3",
    "text2",
    "anNftLikeNoOther2",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft2"
  ],

  icon2: ["icon2", "image3"],
  image3: ["image3"],
  text2: [
    "text2",
    "anNftLikeNoOther2",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft2"
  ],

  anNftLikeNoOther2: ["anNftLikeNoOther2"],
  dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft2:
    [
      "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft2"
    ],

  sectionSmall3: [
    "sectionSmall3",
    "icon3",
    "image4",
    "text3",
    "anNftLikeNoOther3",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft3"
  ],

  icon3: ["icon3", "image4"],
  image4: ["image4"],
  text3: [
    "text3",
    "anNftLikeNoOther3",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft3"
  ],

  anNftLikeNoOther3: ["anNftLikeNoOther3"],
  dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft3:
    [
      "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft3"
    ],

  sectionSmall4: [
    "sectionSmall4",
    "icon4",
    "image5",
    "text4",
    "anNftLikeNoOther4",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft4"
  ],

  icon4: ["icon4", "image5"],
  image5: ["image5"],
  text4: [
    "text4",
    "anNftLikeNoOther4",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft4"
  ],

  anNftLikeNoOther4: ["anNftLikeNoOther4"],
  dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft4:
    [
      "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft4"
    ],

  footer: [
    "footer",
    "bottom",
    "right",
    "left",
    "logo",
    "nftlanding",
    "divider",
    "rectangle9"
  ],

  bottom: ["bottom"],
  right: ["right"],
  left: ["left", "logo", "nftlanding"],
  logo: ["logo", "nftlanding"],
  nftlanding: ["nftlanding"],
  divider: ["divider", "rectangle9"],
  rectangle9: ["rectangle9"],
  img: ["img"],
  call: ["call"],
  hero: [
    "hero",
    "text5",
    "graphic",
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
  ],

  text5: ["text5"],
  graphic: ["graphic", "design82A0Ada5644E4B87Ae4188Faf9684Ea311"],
  design82A0Ada5644E4B87Ae4188Faf9684Ea311: [
    "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
  ],

  group32: ["group32"],
  group31: ["group31"],
  group30: ["group30"],
  group28: ["group28", "group20", "rectangle28"],
  group20: ["group20", "rectangle28"],
  rectangle28: ["rectangle28"],
  sectionSmall5: [
    "sectionSmall5",
    "icon5",
    "image6",
    "text6",
    "anNftLikeNoOther5",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft5"
  ],

  icon5: ["icon5", "image6"],
  image6: ["image6"],
  text6: [
    "text6",
    "anNftLikeNoOther5",
    "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft5"
  ],

  anNftLikeNoOther5: ["anNftLikeNoOther5"],
  dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft5:
    [
      "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft5"
    ],

  group33: ["group33", "group21", "rectangle29"],
  group21: ["group21", "rectangle29"],
  rectangle29: ["rectangle29"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicProfilePage__ArgProps,
          internalVariantPropNames: PlasmicProfilePage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProfilePage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProfilePage";
  } else {
    func.displayName = `PlasmicProfilePage.${nodeName}`;
  }
  return func;
}

export const PlasmicProfilePage = Object.assign(
  // Top-level PlasmicProfilePage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    profilePage: makeNodeComponent("profilePage"),
    sectionSmall: makeNodeComponent("sectionSmall"),
    icon: makeNodeComponent("icon"),
    image2: makeNodeComponent("image2"),
    anNftLikeNoOther: makeNodeComponent("anNftLikeNoOther"),
    dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft:
      makeNodeComponent(
        "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft"
      ),
    sectionSmall2: makeNodeComponent("sectionSmall2"),
    icon2: makeNodeComponent("icon2"),
    image3: makeNodeComponent("image3"),
    text2: makeNodeComponent("text2"),
    anNftLikeNoOther2: makeNodeComponent("anNftLikeNoOther2"),
    dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft2:
      makeNodeComponent(
        "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft2"
      ),
    sectionSmall3: makeNodeComponent("sectionSmall3"),
    icon3: makeNodeComponent("icon3"),
    image4: makeNodeComponent("image4"),
    text3: makeNodeComponent("text3"),
    anNftLikeNoOther3: makeNodeComponent("anNftLikeNoOther3"),
    dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft3:
      makeNodeComponent(
        "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft3"
      ),
    sectionSmall4: makeNodeComponent("sectionSmall4"),
    icon4: makeNodeComponent("icon4"),
    image5: makeNodeComponent("image5"),
    text4: makeNodeComponent("text4"),
    anNftLikeNoOther4: makeNodeComponent("anNftLikeNoOther4"),
    dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft4:
      makeNodeComponent(
        "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft4"
      ),
    footer: makeNodeComponent("footer"),
    bottom: makeNodeComponent("bottom"),
    right: makeNodeComponent("right"),
    left: makeNodeComponent("left"),
    logo: makeNodeComponent("logo"),
    nftlanding: makeNodeComponent("nftlanding"),
    divider: makeNodeComponent("divider"),
    rectangle9: makeNodeComponent("rectangle9"),
    img: makeNodeComponent("img"),
    call: makeNodeComponent("call"),
    hero: makeNodeComponent("hero"),
    text5: makeNodeComponent("text5"),
    graphic: makeNodeComponent("graphic"),
    design82A0Ada5644E4B87Ae4188Faf9684Ea311: makeNodeComponent(
      "design82A0Ada5644E4B87Ae4188Faf9684Ea311"
    ),
    group32: makeNodeComponent("group32"),
    group31: makeNodeComponent("group31"),
    group30: makeNodeComponent("group30"),
    group28: makeNodeComponent("group28"),
    group20: makeNodeComponent("group20"),
    rectangle28: makeNodeComponent("rectangle28"),
    sectionSmall5: makeNodeComponent("sectionSmall5"),
    icon5: makeNodeComponent("icon5"),
    image6: makeNodeComponent("image6"),
    text6: makeNodeComponent("text6"),
    anNftLikeNoOther5: makeNodeComponent("anNftLikeNoOther5"),
    dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft5:
      makeNodeComponent(
        "dontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNftSignUpBelowToReceiveUpdatesWhenWeGoLiveOn189DontMissOutOnTheReleaseOfOurNewNft5"
      ),
    group33: makeNodeComponent("group33"),
    group21: makeNodeComponent("group21"),
    rectangle29: makeNodeComponent("rectangle29"),
    // Metadata about props expected for PlasmicProfilePage
    internalVariantProps: PlasmicProfilePage__VariantProps,
    internalArgProps: PlasmicProfilePage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicProfilePage;
/* prettier-ignore-end */
